defmodule Ankole.Ecto.ActorScheduleIdentityMigrationTest do
  use Ankole.DataCase, async: false

  alias Ankole.Repo

  @migration Ankole.Repo.Migrations.ResetActorScheduleIdentity
  @fire_worker "Elixir.Ankole.SignalsGateway.ActorRuntime.Jobs.FireScheduledEvent"

  unless Code.ensure_loaded?(@migration) do
    Code.require_file(
      Path.expand(
        "../../../priv/repo/migrations/20260722205820_reset_actor_schedule_identity.exs",
        __DIR__
      )
    )
  end

  test "resets legacy UUID schedule state to an empty identity-backed store" do
    create_schedule_fixture!(:uuid)

    Enum.each(@migration.reset_sqls(), &Repo.query!/1)

    assert_reset_schedule_store()
  end

  test "also resets databases already created with an identity key" do
    create_schedule_fixture!(:identity)

    Enum.each(@migration.reset_sqls(), &Repo.query!/1)

    assert_reset_schedule_store()
  end

  test "refuses a lossy downgrade" do
    assert_raise RuntimeError, ~r/cannot be restored/, fn -> @migration.down() end
  end

  defp create_schedule_fixture!(id_type) do
    schema = "actor_schedule_identity_#{System.unique_integer([:positive])}"

    Repo.query!("CREATE SCHEMA #{schema}")
    Repo.query!("SET LOCAL search_path TO #{schema}")

    Repo.query!("CREATE TABLE actor_cron_schedules (id uuid PRIMARY KEY)")
    Repo.query!("CREATE TABLE oban_jobs (id bigint PRIMARY KEY, worker text NOT NULL)")

    Repo.query!("""
    CREATE TABLE actor_scheduled_events (
      id #{id_definition(id_type)},
      cron_schedule_id uuid REFERENCES actor_cron_schedules(id),
      oban_job_id bigint
    )
    """)

    if id_type == :identity do
      Repo.query!("""
      ALTER TABLE actor_scheduled_events
        ADD CONSTRAINT actor_scheduled_events_id_range
        CHECK (id >= 1000 AND id <= 9007199254740991)
      """)
    end

    Repo.query!("""
    INSERT INTO actor_cron_schedules (id)
    VALUES ('00000000-0000-0000-0000-000000000001')
    """)

    Repo.query!("""
    INSERT INTO oban_jobs (id, worker)
    VALUES
      (1, '#{@fire_worker}'),
      (2, 'Elixir.Ankole.UnrelatedWorker')
    """)

    insert_scheduled_event!(id_type)
  end

  defp id_definition(:uuid), do: "uuid PRIMARY KEY"

  defp id_definition(:identity),
    do: "bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY"

  defp insert_scheduled_event!(:uuid) do
    Repo.query!("""
    INSERT INTO actor_scheduled_events (id, cron_schedule_id, oban_job_id)
    VALUES (
      '00000000-0000-0000-0000-000000000002',
      '00000000-0000-0000-0000-000000000001',
      1
    )
    """)
  end

  defp insert_scheduled_event!(:identity) do
    Repo.query!("""
    INSERT INTO actor_scheduled_events (cron_schedule_id, oban_job_id)
    VALUES ('00000000-0000-0000-0000-000000000001', 1)
    """)
  end

  defp assert_reset_schedule_store do
    assert [[0, 0]] =
             Repo.query!("""
             SELECT
               (SELECT count(*) FROM actor_scheduled_events),
               (SELECT count(*) FROM actor_cron_schedules)
             """).rows

    assert [[2, "Elixir.Ankole.UnrelatedWorker"]] =
             Repo.query!("SELECT id, worker FROM oban_jobs").rows

    assert [["bigint", "YES"]] =
             Repo.query!("""
             SELECT data_type, is_identity
             FROM information_schema.columns
             WHERE table_schema = current_schema()
               AND table_name = 'actor_scheduled_events'
               AND column_name = 'id'
             """).rows

    assert [["actor_scheduled_events_id_range"]] =
             Repo.query!("""
             SELECT conname
             FROM pg_constraint
             WHERE conrelid = 'actor_scheduled_events'::regclass
               AND conname = 'actor_scheduled_events_id_range'
             """).rows

    assert [[1000]] =
             Repo.query!("INSERT INTO actor_scheduled_events DEFAULT VALUES RETURNING id").rows
  end
end
