import Config

webapps_path = Path.expand("../../webapps", __DIR__)

# Configure your database
config :ankole, Ankole.Repo,
  username: "postgres",
  password: System.get_env("POSTGRES_PASSWORD") || "just4local-dev",
  hostname: "localhost",
  port: String.to_integer(System.get_env("POSTGRES_PORT") || "5433"),
  database: "ankole_dev",
  template: "template0",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
config :ankole, AnkoleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "c7RU/wpQbiQz5i/sPyIgbjZbL/tbpqTmqcMvppOoAzeQCKN/oHaEpyVoK5cNAeTQ",
  watchers: [
    bun: ["run", "dev", cd: webapps_path]
  ]

config :ankole, AnkoleWeb.Assets, dev_server: "http://127.0.0.1:3035"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :ankole, AnkoleWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, controllers, and templates
      ~r"lib/ankole_web/router\.ex$"E,
      ~r"lib/ankole_web/(controllers|components)/.*\.(ex|eex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ankole, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
