# syntax=docker/dockerfile:1.7

ARG BASE_IMAGE=ankole-agent-computer:0.1.0

FROM ${BASE_IMAGE}

WORKDIR /repo

COPY internals/skills ./internals/skills

ENV ANKOLE_INTERNAL_SKILLS_ROOT=/repo/internals/skills
