import type { Rule, Tree } from '@angular-devkit/schematics'
import { jsonc } from 'jsonc'

type CodeWorkspaceOptions = {
  file?: string
}

type CodeWorkspace = {
  folders?: Array<{
    name: string
    path: string
  }>
  [key: string]: unknown
}

type RootPackageJson = {
  workspaces?:
    | string[]
    | {
        packages?: string[]
      }
}

export function workspace(options: CodeWorkspaceOptions = {}): Rule {
  return tree => {
    const workspaceFile = options.file ?? 'ankole.code-workspace'
    const currentWorkspace = readCodeWorkspace(tree, workspaceFile)

    currentWorkspace.folders = [
      {
        name: './',
        path: '.'
      },
      ...currentBunWorkspaces(tree).map(location => ({
        name: `./${location}`,
        path: location
      }))
    ]

    const output = [
      '// DO NOT MODIFY THE `folders` FIELD MANUALLY.',
      '// It can be generated by `bun run kit g code-workspace`.',
      jsonc.stringify(currentWorkspace, { space: 2 }),
      ''
    ].join('\n')

    if (tree.exists(workspaceFile)) {
      tree.overwrite(workspaceFile, output)
      return tree
    }

    tree.create(workspaceFile, output)
    return tree
  }
}

function readCodeWorkspace(tree: Tree, path: string): CodeWorkspace {
  const current = tree.read(path)
  if (!current) return {}

  return jsonc.parse(current.toString('utf8')) as CodeWorkspace
}

function currentBunWorkspaces(tree: Tree): string[] {
  const rootPackage = readJson<RootPackageJson>(tree, 'package.json')
  const patterns = Array.isArray(rootPackage.workspaces)
    ? rootPackage.workspaces
    : (rootPackage.workspaces?.packages ?? [])

  return [...new Set(patterns.flatMap(pattern => expandWorkspacePattern(tree, pattern)))]
    .filter(location => tree.exists(`${location}/package.json`))
    .sort((a, b) => a.localeCompare(b))
}

function expandWorkspacePattern(tree: Tree, pattern: string): string[] {
  if (!pattern.includes('*')) return [pattern]

  const starIndex = pattern.indexOf('*')
  const prefix = pattern.slice(0, starIndex).replace(/\/$/, '')
  const suffix = pattern.slice(starIndex + 1).replace(/^\//, '')
  const dir = tree.getDir(prefix || '.')
  const locations: string[] = []

  for (const subdir of dir.subdirs) {
    const location = [prefix, subdir, suffix].filter(Boolean).join('/')
    locations.push(location)
  }

  return locations
}

function readJson<TValue>(tree: Tree, path: string): TValue {
  const content = tree.read(path)
  if (!content) throw new Error(`Expected ${path} to exist`)

  return JSON.parse(content.toString('utf8')) as TValue
}
