/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Bun/Node DEALER-side RuntimeFabric client. */
export declare class RuntimeFabricDealer {
  constructor(endpoint: string, identity: string, username: string, password: string)
  sendEnvelope(envelope: any): void
  sendFileFrame(frames: Buffer[]): void
  recvRawAsync(timeoutMs: number): Promise<Buffer[] | null>
  stop(): void
}
export type JsRuntimeFabricDealer = RuntimeFabricDealer

/** Authorizes one exact action on one concrete resource. */
export declare function authzAuthorize(snapshot: any): any

/** Authorizes every requested action against the same concrete resource. */
export declare function authzAuthorizeAll(snapshot: any): any

/** Returns whether a resource pattern matches a concrete resource key. */
export declare function authzMatchResourcePattern(pattern: string, resource: string): boolean

/** Returns whether a CEL authorization condition compiles. */
export declare function authzValidateCondition(condition: string): boolean

/** Returns whether a resource pattern is valid. */
export declare function authzValidateResourcePattern(pattern: string): boolean

export declare function estimateO200kBaseTokens(text: string): number

/** Hashes binary data through the shared kernel `generic_hash` contract. */
export declare function genericHash(data: Buffer): string

/** Decodes RuntimeFabric v1 protobuf bytes into a JSON-shaped envelope. */
export declare function runtimeFabricDecodeEnvelope(bytes: Buffer): any

/** Encodes a RuntimeFabric v1 envelope into protobuf bytes. */
export declare function runtimeFabricEncodeEnvelope(envelope: any): Buffer

/** Evaluates a SignalsGateway CEL admission filter. */
export declare function signalsGatewayFilterMatch(filterSource: string, context: any): boolean

/** Returns whether a SignalsGateway CEL admission filter compiles. */
export declare function signalsGatewayValidateFilter(filterSource: string): boolean

/** Computes a standard unified text diff body using the native kernel diff primitive. */
export declare function unifiedTextDiff(before: string, after: string, contextLines: number): Promise<string>

/** Parses a web URL with WHATWG semantics and classifies its host. */
export declare function webURLFacts(url: string): WebURLFacts

/** Facts about one parsed web URL for the shared web tools URL policy. */
export interface WebURLFacts {
  scheme: string
  host?: string
  hostClass?: 'metadata' | 'private' | 'public' | null
}

/** Computes the non-cryptographic XXH3 128-bit observation fingerprint. */
export declare function xxh3File128Hex(path: string): string

/** Computes the non-cryptographic XXH3 128-bit fingerprint for a UTF-8 string. */
export declare function xxh3String128Hex(input: string): string

/**
 * Compresses one worker-file lane block into a self-contained zstd frame.
 *
 * Runs on a libuv worker thread so the JS event loop is not blocked while a
 * block is being compressed. `level` follows the zstd CLI scale (1..=22).
 */
export declare function zstdCompressBlock(data: Buffer, level: number): Promise<Buffer>

/**
 * Decompresses one worker-file lane zstd frame with a hard output bound.
 *
 * `max_out` rejects oversized payloads, capping zip-bomb exposure at one block.
 * Runs on a libuv worker thread so the JS event loop is not blocked.
 */
export declare function zstdDecompressBlock(data: Buffer, maxOut: number): Promise<Buffer>
