name: "bullx-external-services"
services:
  rds:
    image: pgvector/pgvector:pg18
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - COMPOSE_PROJECT_NAME
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=just4local-dev
    ports:
      - 5433:5432
    volumes:
      - rds_data:/var/lib/pgsql/18/data
  redis:
    image: redis:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 6379:6379
  redis_test:
    image: redis:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 6380:6379

volumes:
  rds_data:
