import { describe, expect, it } from 'bun:test'
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative } from 'node:path'

const checkedInProtocolRoot = join(import.meta.dir, '../../src/tools/subagent/generated/protocol')

describe('@ankole/agent-computer Codex app-server protocol contract', () => {
  it('runs the Codex version pinned by the worker image', async () => {
    const proc = Bun.spawn(['codex', '--version'], { stdout: 'pipe', stderr: 'pipe' })
    const [exitCode, stdout, stderr] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text()
    ])

    expect(exitCode).toBe(0)
    expect(`${stdout}${stderr}`.trim()).toBe('codex-cli 0.144.0')
  })

  it('can execute the Codex Linux sandbox inside the worker container', async () => {
    const proc = Bun.spawn(['codex', 'sandbox', '/bin/true'], { stdout: 'pipe', stderr: 'pipe' })
    const [exitCode, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])

    expect(stderr).toBe('')
    expect(exitCode).toBe(0)
  })

  it('matches the experimental TypeScript bindings generated by the pinned Codex binary', async () => {
    const generatedRoot = mkdtempSync(join(tmpdir(), 'ankole-codex-protocol-'))

    try {
      const proc = Bun.spawn(['codex', 'app-server', 'generate-ts', '--experimental', '--out', generatedRoot], {
        stdout: 'pipe',
        stderr: 'pipe'
      })
      const [exitCode, stdout, stderr] = await Promise.all([
        proc.exited,
        new Response(proc.stdout).text(),
        new Response(proc.stderr).text()
      ])

      expect(`${stdout}\n${stderr}`).toBeString()
      expect(exitCode).toBe(0)
      expect(protocolFiles(checkedInProtocolRoot)).toEqual(protocolFiles(generatedRoot))

      for (const file of protocolFiles(generatedRoot)) {
        expect(readFileSync(join(checkedInProtocolRoot, file), 'utf8')).toBe(
          readFileSync(join(generatedRoot, file), 'utf8')
        )
      }
    } finally {
      rmSync(generatedRoot, { recursive: true, force: true })
    }
  })
})

function protocolFiles(root: string): string[] {
  return readdirSync(root, { recursive: true, withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.ts'))
    .map(entry => relative(root, join(entry.parentPath, entry.name)))
    .sort()
}
