import { describe, expect, it } from 'bun:test'
import { create } from '@bufbuild/protobuf'
import { jsonBytes } from '../../src/fabric/envelope_proto'
import {
  AIGatewayAPIKeyResponseSchema,
  RuntimeSkillSummarySchema,
  SkillOverlayResponseSchema
} from '../../src/fabric/generated/ankole/runtime_fabric/v1/rpc_pb'
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative } from 'node:path'
import { CodexAppServerClient } from '../../src/tools/codex/app-server-client'
import type { HooksListResponse } from '../../src/tools/codex/generated/protocol/v2/HooksListResponse'
import { materializeCodexConfig } from '../../src/tools/codex/config'
import { codexAppServerSandboxSpec } from '../../src/tools/codex/sandbox'
import { materializeCodexJobRuntimeFiles, renderCodexJobAgents } from '../../src/core/codex-runner/runtime-files'
import { prepareCodexJobProject } from '../../src/core/codex-runner/job-project'
import { materializeCodexJobProjectConfig } from '../../src/core/codex-runner/project-config'
import { rpcMethods, type RPCRequester } from '../../src/lanes/rpc_lane'
import type { CodexRuntimeConfig } from '../../src/tools/codex/runtime-config'

const checkedInProtocolRoot = join(import.meta.dir, '../../src/tools/codex/generated/protocol')

describe('@ankole/agent-computer Codex app-server protocol contract', () => {
  it('runs the Codex version pinned by the worker image', async () => {
    const proc = Bun.spawn(['codex', '--version'], { stdout: 'pipe', stderr: 'pipe' })
    const [exitCode, stdout, stderr] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text()
    ])

    expect(exitCode).toBe(0)
    expect(`${stdout}${stderr}`.trim()).toBe('codex-cli 0.146.0')
  })

  it('can execute the Codex Linux sandbox inside the worker container', async () => {
    const proc = Bun.spawn(['codex', 'sandbox', '/bin/true'], { stdout: 'pipe', stderr: 'pipe' })
    const [exitCode, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])

    expect(stderr).toBe('')
    expect(exitCode).toBe(0)
  })

  it('matches the experimental TypeScript bindings generated by the pinned Codex binary', async () => {
    const generatedRoot = mkdtempSync(join(tmpdir(), 'ankole-codex-protocol-'))

    try {
      const proc = Bun.spawn(['codex', 'app-server', 'generate-ts', '--experimental', '--out', generatedRoot], {
        stdout: 'pipe',
        stderr: 'pipe'
      })
      const [exitCode, stdout, stderr] = await Promise.all([
        proc.exited,
        new Response(proc.stdout).text(),
        new Response(proc.stderr).text()
      ])

      expect(`${stdout}\n${stderr}`).toBeString()
      expect(exitCode).toBe(0)
      expect(protocolFiles(checkedInProtocolRoot)).toEqual(protocolFiles(generatedRoot))

      for (const file of protocolFiles(generatedRoot)) {
        expect(readFileSync(join(checkedInProtocolRoot, file), 'utf8')).toBe(
          readFileSync(join(generatedRoot, file), 'utf8')
        )
      }
    } finally {
      rmSync(generatedRoot, { recursive: true, force: true })
    }
  })

  it('discovers standalone skills after replacing process extra roots', async () => {
    const root = mkdtempSync(join(tmpdir(), 'ankole-codex-native-skills-'))
    const workspace = join(root, 'workspace')
    const codexHome = join(root, 'codex-home')
    const skillsRoot = join(root, 'skills')
    const skillRoot = join(skillsRoot, 'pptx')
    mkdirSync(workspace, { recursive: true })
    mkdirSync(codexHome, { recursive: true })
    mkdirSync(skillRoot, { recursive: true })
    writeFileSync(
      join(skillRoot, 'SKILL.md'),
      ['---', 'name: pptx', 'description: Create PowerPoint presentations.', '---', '', '# PPTX', ''].join('\n')
    )

    const client = new CodexAppServerClient({
      cwd: workspace,
      env: {
        PATH: process.env.PATH ?? '/usr/local/bin:/usr/bin:/bin',
        HOME: workspace,
        CODEX_HOME: codexHome,
        CODEX_UNSAFE_ALLOW_NO_SANDBOX: '1',
        LANG: 'C.UTF-8'
      }
    })

    try {
      await client.initialize()
      await client.request('skills/extraRoots/set', { extraRoots: [skillsRoot] })
      const response = (await client.request('skills/list', {
        cwds: [workspace],
        forceReload: true
      })) as { data: Array<{ skills: Array<{ name: string; path: string; enabled: boolean }> }> }

      expect(response.data[0]?.skills.find(skill => skill.name === 'pptx')).toMatchObject({
        name: 'pptx',
        path: join(skillRoot, 'SKILL.md'),
        enabled: true
      })
    } finally {
      await client.close()
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('loads official plugins, project config, and trusted hooks from a private non-Git job project', async () => {
    const root = mkdtempSync(join(tmpdir(), 'ankole-codex-job-project-'))
    const projectRoot = join(root, 'project')
    const codexHome = join(root, 'codex-home')
    const marketplacePath = join(projectRoot, '.agents', 'plugins', 'marketplace.json')
    const defaultPluginRoot = join(projectRoot, 'plugins', 'default-hooks')
    const explicitPluginRoot = join(projectRoot, 'plugins', 'explicit-hooks')
    mkdirSync(join(projectRoot, '.agents', 'plugins'), { recursive: true })
    mkdirSync(join(projectRoot, '.codex'), { recursive: true })
    mkdirSync(join(defaultPluginRoot, '.codex-plugin'), { recursive: true })
    mkdirSync(join(defaultPluginRoot, 'skills', 'default-skill'), { recursive: true })
    mkdirSync(join(defaultPluginRoot, 'hooks'), { recursive: true })
    mkdirSync(join(explicitPluginRoot, '.codex-plugin'), { recursive: true })
    mkdirSync(join(explicitPluginRoot, 'skills', 'explicit-skill'), { recursive: true })
    mkdirSync(join(explicitPluginRoot, 'policies'), { recursive: true })
    mkdirSync(codexHome, { recursive: true })

    writeFileSync(
      marketplacePath,
      JSON.stringify({
        name: 'ankole-job',
        plugins: [
          {
            name: 'default-hooks',
            source: { source: 'local', path: './plugins/default-hooks' },
            policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
            category: 'Developer Tools'
          },
          {
            name: 'explicit-hooks',
            source: { source: 'local', path: './plugins/explicit-hooks' },
            policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
            category: 'Developer Tools'
          }
        ]
      })
    )
    writeFileSync(
      join(defaultPluginRoot, '.codex-plugin', 'plugin.json'),
      JSON.stringify({
        name: 'default-hooks',
        version: '1.0.0',
        description: 'Default hook discovery contract.',
        skills: './skills/'
      })
    )
    writeFileSync(
      join(defaultPluginRoot, 'skills', 'default-skill', 'SKILL.md'),
      ['---', 'name: default-skill', 'description: Default plugin skill.', '---', '', '# Default skill', ''].join('\n')
    )
    writeFileSync(
      join(defaultPluginRoot, 'hooks', 'hooks.json'),
      JSON.stringify({
        hooks: {
          SessionStart: [{ hooks: [{ type: 'command', command: '/bin/true' }] }]
        }
      })
    )
    writeFileSync(
      join(explicitPluginRoot, '.codex-plugin', 'plugin.json'),
      JSON.stringify({
        name: 'explicit-hooks',
        version: '1.0.0',
        description: 'Explicit hook discovery contract.',
        skills: './skills/',
        hooks: './policies/hooks.json'
      })
    )
    writeFileSync(
      join(explicitPluginRoot, 'skills', 'explicit-skill', 'SKILL.md'),
      ['---', 'name: explicit-skill', 'description: Explicit plugin skill.', '---', '', '# Explicit skill', ''].join(
        '\n'
      )
    )
    writeFileSync(
      join(explicitPluginRoot, 'policies', 'hooks.json'),
      JSON.stringify({
        hooks: {
          UserPromptSubmit: [{ hooks: [{ type: 'command', command: '/bin/true' }] }]
        }
      })
    )

    const trustedProjectKey = projectRoot.replaceAll('\\', '\\\\').replaceAll('"', '\\"')
    writeFileSync(
      join(codexHome, 'config.toml'),
      `[features]\nplugins = true\nremote_plugin = false\n\n[projects."${trustedProjectKey}"]\ntrust_level = "trusted"\n`
    )
    writeFileSync(
      join(projectRoot, '.codex', 'config.toml'),
      [
        'model_reasoning_effort = "medium"',
        'web_search = "disabled"',
        '',
        '[features.multi_agent_v2]',
        'enabled = true',
        'hide_spawn_agent_metadata = true',
        'max_concurrent_threads_per_session = 1',
        ''
      ].join('\n')
    )

    const stderrChunks: string[] = []
    const client = new CodexAppServerClient({
      cwd: projectRoot,
      env: {
        PATH: process.env.PATH ?? '/usr/local/bin:/usr/bin:/bin',
        HOME: projectRoot,
        CODEX_HOME: codexHome,
        CODEX_UNSAFE_ALLOW_NO_SANDBOX: '1',
        LANG: 'C.UTF-8'
      },
      onNotification: message => {
        if (message.method === '$stderr' && typeof (message.params as { text?: unknown })?.text === 'string') {
          stderrChunks.push((message.params as { text: string }).text)
        }
      }
    })

    try {
      await client.initialize()
      for (const pluginName of ['default-hooks', 'explicit-hooks']) {
        await client.request('plugin/install', { marketplacePath, pluginName })
      }

      const installed = (await client.request('plugin/installed', { cwds: [projectRoot] })) as {
        marketplaces: Array<{ plugins: Array<{ name: string; installed: boolean; enabled: boolean }> }>
      }
      expect(
        installed.marketplaces
          .flatMap(marketplace => marketplace.plugins)
          .filter(plugin => ['default-hooks', 'explicit-hooks'].includes(plugin.name))
          .map(plugin => ({ name: plugin.name, installed: plugin.installed, enabled: plugin.enabled }))
          .sort((left, right) => left.name.localeCompare(right.name))
      ).toEqual([
        { name: 'default-hooks', installed: true, enabled: true },
        { name: 'explicit-hooks', installed: true, enabled: true }
      ])

      const skills = (await client.request('skills/list', {
        cwds: [projectRoot],
        forceReload: true
      })) as { data: Array<{ skills: Array<{ name: string }> }> }
      expect(skills.data[0]?.skills.map(skill => skill.name)).toEqual(
        expect.arrayContaining(['default-hooks:default-skill', 'explicit-hooks:explicit-skill'])
      )

      const firstHooks = (await client.request('hooks/list', { cwds: [projectRoot] })) as HooksListResponse
      const pluginHooks = firstHooks.data[0]?.hooks.filter(hook => hook.pluginId) ?? []
      expect(pluginHooks.map(hook => hook.pluginId).sort()).toEqual([
        'default-hooks@ankole-job',
        'explicit-hooks@ankole-job'
      ])
      expect(pluginHooks.every(hook => hook.enabled && hook.trustStatus === 'untrusted')).toBe(true)

      await client.request('config/batchWrite', {
        edits: [
          {
            keyPath: 'hooks.state',
            value: Object.fromEntries(pluginHooks.map(hook => [hook.key, { trusted_hash: hook.currentHash }])),
            mergeStrategy: 'upsert'
          }
        ],
        reloadUserConfig: true
      })
      const trustedHooks = (await client.request('hooks/list', { cwds: [projectRoot] })) as HooksListResponse
      expect(
        trustedHooks.data[0]?.hooks.filter(hook => hook.pluginId).every(hook => hook.trustStatus === 'trusted')
      ).toBe(true)

      const config = (await client.request('config/read', { cwd: projectRoot, includeLayers: true })) as {
        config: { model_reasoning_effort?: string }
        layers: Array<{ name: { type: string }; disabledReason: string | null }> | null
      }
      expect(config.config.model_reasoning_effort).toBe('medium')
      const projectLayer = config.layers?.find(layer => layer.name.type === 'project')
      expect(projectLayer).toBeDefined()
      expect(
        projectLayer && (!Object.hasOwn(projectLayer, 'disabledReason') || projectLayer.disabledReason === null)
      ).toBe(true)

      const thread = (await client.request('thread/start', {
        cwd: projectRoot,
        approvalPolicy: 'never',
        sandbox: 'danger-full-access',
        config: { model_reasoning_effort: 'high' }
      })) as { reasoningEffort: string | null }
      expect(thread.reasoningEffort).toBe('high')

      await client.close()
      const resumedClient = new CodexAppServerClient({
        cwd: projectRoot,
        env: {
          PATH: process.env.PATH ?? '/usr/local/bin:/usr/bin:/bin',
          HOME: projectRoot,
          CODEX_HOME: codexHome,
          CODEX_UNSAFE_ALLOW_NO_SANDBOX: '1',
          LANG: 'C.UTF-8'
        }
      })
      try {
        await resumedClient.initialize()
        for (const pluginName of ['default-hooks', 'explicit-hooks']) {
          await resumedClient.request('plugin/install', { marketplacePath, pluginName })
        }
        const reinstalled = (await resumedClient.request('plugin/installed', { cwds: [projectRoot] })) as {
          marketplaces: Array<{ plugins: Array<{ name: string; installed: boolean; enabled: boolean }> }>
        }
        expect(
          reinstalled.marketplaces
            .flatMap(marketplace => marketplace.plugins)
            .filter(plugin => ['default-hooks', 'explicit-hooks'].includes(plugin.name))
            .every(plugin => plugin.installed && plugin.enabled)
        ).toBe(true)
        const resumedSkills = (await resumedClient.request('skills/list', {
          cwds: [projectRoot],
          forceReload: true
        })) as { data: Array<{ skills: Array<{ name: string }> }> }
        expect(resumedSkills.data[0]?.skills.map(skill => skill.name)).toEqual(
          expect.arrayContaining(['default-hooks:default-skill', 'explicit-hooks:explicit-skill'])
        )
        const resumedHooks = (await resumedClient.request('hooks/list', { cwds: [projectRoot] })) as HooksListResponse
        expect(
          resumedHooks.data[0]?.hooks.filter(hook => hook.pluginId).every(hook => hook.trustStatus === 'trusted')
        ).toBe(true)
      } finally {
        await resumedClient.close()
      }
    } catch (error) {
      throw new Error(`${error instanceof Error ? error.message : String(error)}\n${stderrChunks.join('')}`)
    } finally {
      await client.close()
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('uses real Job and Skill paths inside the bubblewrap sandbox', async () => {
    const root = mkdtempSync('/agents/ankole-codex-contract-')
    const jobProjectRoot = join(root, 'agent-1', 'jobs', '1000')
    const builtinSkillsRoot = join(root, 'skills')
    const skillRoot = join(builtinSkillsRoot, 'pptx')
    const fakeCodex = join(jobProjectRoot, 'fake-codex')
    const previousCodexBinary = process.env.ANKOLE_CODEX_BINARY
    mkdirSync(jobProjectRoot, { recursive: true })
    mkdirSync(skillRoot, { recursive: true })
    writeFileSync(
      join(skillRoot, 'SKILL.md'),
      ['---', 'name: pptx', 'description: Create PowerPoint presentations.', '---', '', '# PPTX', ''].join('\n')
    )
    writeFileSync(
      fakeCodex,
      `#!/bin/sh
set -eu
grep -q 'TASK_AGENTS_MARKER' ${jobProjectRoot}/AGENTS.md
grep -q '# PPTX' ${jobProjectRoot}/.ankole/skills/pptx/SKILL.md
grep -q 'PG_OVERLAY_MARKER' ${jobProjectRoot}/.ankole/skills/pptx/SKILL.md
grep -q '^name: pdf$' /repo/app/library/skills/pdf/SKILL.md
grep -q '^model = "gpt-5.6-sol"$' ${jobProjectRoot}/.codex/config.toml
grep -q '^model_provider = "ankole_aigateway"$' \${CODEX_HOME}/config.toml
test -n "\${ANKOLE_AIGATEWAY_MODEL_BINDING:-}"
printf 'command path works\n' > ${jobProjectRoot}/command-probe.txt
test "$(bun -e "const { genericHash } = require('/repo/app/kernel'); process.stdout.write(genericHash(Buffer.from('bullx')))")" = '7f31cabae40697f9404428671c582d3c1f80c8a13d0741f4be8c9b856fcc0706'
test ! -e ./AGENTS.override.md
`
    )
    chmodSync(fakeCodex, 0o755)

    const project = prepareCodexJobProject({ jobProjectRoot })
    const renderedAgents = renderCodexJobAgents({
      jobRoot: project.root,
      soul: 'TASK_AGENTS_MARKER',
      mission: 'Verify runtime mounts.'
    })
    writeFileSync(join(jobProjectRoot, 'AGENTS.md'), renderedAgents.content)
    const runtimeInput: Parameters<typeof materializeCodexJobRuntimeFiles>[0] = {
      turn: {
        actor: { agent_uid: 'agent-1', session_id: 'job:1000' },
        activation_uid: 'activation-1',
        actor_epoch: 1,
        actor_event_id: '00000000-0000-0000-0000-000000000001',
        revision: 0
      },
      jobRoot: project.root,
      enabledSkills: [
        create(RuntimeSkillSummarySchema, {
          skillName: 'pptx',
          sourceKind: 'builtin',
          relativePath: 'pptx',
          hasAgentOverlay: true
        })
      ],
      skillRoots: {
        builtinSkillsRoot,
        agentInstalledSkillsRoot: join(root, 'installed-skills')
      },
      rpc: (async (method: unknown, payload: unknown) => {
        if (method !== rpcMethods.skillsOverlayResolve) throw new Error(`unexpected RPC method: ${String(method)}`)
        const request = payload as { skillName: string }
        return create(SkillOverlayResponseSchema, {
          skillName: request.skillName,
          hasOverlay: true,
          overlayJson: jsonBytes({ text: 'PG_OVERLAY_MARKER' }),
          contentHash: 'overlay-hash'
        })
      }) as RPCRequester
    }
    const runtimeFiles = await materializeCodexJobRuntimeFiles(runtimeInput)
    const runtimeConfig: CodexRuntimeConfig = {
      modelProfile: {
        model: 'gpt-5.6-sol',
        selector: 'openrouter/openai/gpt-5.6-sol',
        providerOptions: { reasoningEffort: 'xhigh' },
        supportsParallelToolCalls: true,
        modelReasoningEffort: 'xhigh'
      },
      aiGatewayKey: create(AIGatewayAPIKeyResponseSchema, {
        agentUid: 'agent-1',
        apiKey: 'unused-test-key',
        tokenType: 'Bearer',
        expiresAt: BigInt(Math.floor(Date.now() / 1_000) + 3_600),
        expiresIn: 3_600n,
        scope: 'ai_gateway',
        baseUrl: 'http://control.test/api/v1/ai-gateway'
      })
    }
    const materialized = materializeCodexConfig({
      agentsRoot: root,
      agentUID: 'agent-1',
      runtime: runtimeConfig
    })
    materializeCodexJobProjectConfig({
      projectRoot: project.root,
      pluginsEnabled: false,
      runtimeConfig
    })
    let realClient: CodexAppServerClient | undefined

    try {
      process.env.ANKOLE_CODEX_BINARY = fakeCodex
      const sandbox = codexAppServerSandboxSpec({ project, materialized, runtimeFiles })
      const proc = Bun.spawn(sandbox.commandArgv, {
        cwd: sandbox.cwd,
        env: sandbox.env,
        stdin: 'ignore',
        stdout: 'pipe',
        stderr: 'pipe'
      })
      const [exitCode, stdout, stderr] = await Promise.all([
        proc.exited,
        new Response(proc.stdout).text(),
        new Response(proc.stderr).text()
      ])

      expect(stdout).toBe('')
      expect(stderr).toBeString()
      expect(exitCode).toBe(0)
      expect(readFileSync(join(jobProjectRoot, 'command-probe.txt'), 'utf8')).toBe('command path works\n')
      expect(existsSync(join(jobProjectRoot, 'AGENTS.override.md'))).toBe(false)
      expect(readFileSync(join(skillRoot, 'SKILL.md'), 'utf8')).not.toContain('PG_OVERLAY_MARKER')

      if (previousCodexBinary === undefined) delete process.env.ANKOLE_CODEX_BINARY
      else process.env.ANKOLE_CODEX_BINARY = previousCodexBinary
      const realSandbox = codexAppServerSandboxSpec({ project, materialized, runtimeFiles })
      const stderrChunks: string[] = []
      realClient = new CodexAppServerClient({
        cwd: realSandbox.cwd,
        env: realSandbox.env,
        commandArgv: realSandbox.commandArgv,
        onNotification: message => {
          if (message.method === '$stderr' && typeof (message.params as { text?: unknown })?.text === 'string') {
            stderrChunks.push((message.params as { text: string }).text)
          }
        }
      })

      try {
        const initializeResponse = await realClient.initialize()
        expect(initializeResponse.userAgent).toStartWith('codex_cli_rs/0.146.0 ')
        await realClient.request('skills/extraRoots/set', { extraRoots: [runtimeFiles.skillsRoot] })
        const response = (await realClient.request('skills/list', {
          cwds: [realSandbox.codexCwd],
          forceReload: true
        })) as { data: Array<{ skills: Array<{ name: string; path: string; enabled: boolean }> }> }
        expect(response.data[0]?.skills.find(skill => skill.name === 'pptx')).toMatchObject({
          name: 'pptx',
          path: `${runtimeFiles.skillsRoot}/pptx/SKILL.md`,
          enabled: true
        })
        const thread = (await realClient.request('thread/start', {
          cwd: realSandbox.codexCwd,
          approvalPolicy: 'never',
          sandbox: 'danger-full-access'
        })) as {
          instructionSources: string[]
          model: string
          modelProvider: string
          reasoningEffort: string | null
        }
        expect(thread.instructionSources.some(path => path.endsWith('/AGENTS.md'))).toBe(true)
        expect(thread.instructionSources).toHaveLength(1)
        expect(thread.model).toBe('gpt-5.6-sol')
        expect(thread.modelProvider).toBe('ankole_aigateway')
        expect(thread.reasoningEffort).toBe('xhigh')
      } catch (error) {
        throw new Error(`${error instanceof Error ? error.message : String(error)}\n${stderrChunks.join('')}`)
      }
    } finally {
      await realClient?.close()
      if (previousCodexBinary === undefined) delete process.env.ANKOLE_CODEX_BINARY
      else process.env.ANKOLE_CODEX_BINARY = previousCodexBinary
      runtimeFiles.cleanup()
      rmSync(root, { recursive: true, force: true })
    }
  }, 20_000)
})

function protocolFiles(root: string): string[] {
  return readdirSync(root, { recursive: true, withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.ts'))
    .map(entry => relative(root, join(entry.parentPath, entry.name)))
    .sort()
}
