defmodule Ankole.Ecto.UUIDv7 do
  @moduledoc """
  Ecto UUID type whose autogenerated values come from the Ankole kernel.

  The type stores the same PostgreSQL `uuid` value as `Ecto.UUID`; it exists so
  Ankole row identifiers use the shared Rust `gen_uuid_v7/0` implementation
  instead of each host runtime choosing its own generator.
  """

  use Ecto.Type

  alias Ankole.Kernel, as: NativeKernel

  @type t :: Ecto.UUID.t()

  @doc """
  Returns the database storage type for Ankole UUIDv7 ids.
  """
  @spec type() :: :uuid
  def type, do: :uuid

  @doc """
  Casts external UUID values using the standard Ecto UUID codec.
  """
  @spec cast(term()) :: {:ok, t()} | :error
  def cast(value), do: Ecto.UUID.cast(value)

  @doc """
  Loads database UUID values using the standard Ecto UUID codec.
  """
  @spec load(term()) :: {:ok, t()} | :error
  def load(value), do: Ecto.UUID.load(value)

  @doc """
  Dumps UUID values using the standard Ecto UUID codec.
  """
  @spec dump(term()) :: {:ok, Ecto.UUID.raw()} | :error
  def dump(value), do: Ecto.UUID.dump(value)

  @doc """
  Generates a UUIDv7 value through the shared native kernel.
  """
  @spec autogenerate() :: t()
  def autogenerate, do: NativeKernel.gen_uuid_v7()
end
