defmodule Ankole.Ecto.UUIDv7 do
  @moduledoc """
  Ecto UUID type whose autogenerated values come from the Ankole kernel.

  The type stores the same PostgreSQL `uuid` value as `Ecto.UUID`; it exists so
  Ankole row identifiers use the shared Rust `gen_uuid_v7/0` implementation
  instead of each host runtime choosing its own generator.
  """

  use Ecto.Type

  alias Ankole.Kernel, as: NativeKernel

  @type t :: Ecto.UUID.t()

  @doc false
  def type, do: :uuid

  @doc false
  def cast(value), do: Ecto.UUID.cast(value)

  @doc false
  def load(value), do: Ecto.UUID.load(value)

  @doc false
  def dump(value), do: Ecto.UUID.dump(value)

  @doc false
  def autogenerate, do: NativeKernel.gen_uuid_v7()
end
