/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Decrypts a message using XChaCha20-Poly1305-IETF
 * @param cipher - base64 url-safe encoded ciphertext with nonce
 * @param key - 32bytes encryption key
 * @returns plaintext buffer
 */
export declare function aeadDecrypt(cipher: string, key: string): Buffer

/**
 * Encrypts a message using XChaCha20-Poly1305-IETF
 * @param plain - plaintext
 * @param key - 32bytes encryption key
 * @returns ciphertext - base64 url-safe encoded ciphertext with nonce
 */
export declare function aeadEncrypt(plain: string | Buffer, key: string): string

/**
 * AnyAscii provides ASCII-only replacement strings for practically
 * all Unicode characters.
 * @param input Any unicode string
 * @returns ASCII-only string
 */
export declare function anyAscii(input: string): string

export declare function authzAuthorize(snapshot: any): any

export declare function authzAuthorizeAll(snapshot: any): any

export declare function authzMatchResourcePattern(pattern: string, resource: string): boolean

export declare function authzValidateCondition(condition: string): boolean

export declare function authzValidateResourcePattern(pattern: string): boolean

/**
 * Base58 decoding (Bitcoin style)
 * @param input base58 encoded string
 * @returns decoded buffer
 */
export declare function base58Decode(input: string): Buffer

/**
 * Base58 encoding (Bitcoin style)
 * @param input string or buffer
 * @returns base58 encoded string
 */
export declare function base58Encode(input: string | Buffer): string

/**
 * Base64 decoding (url safe)
 * @param input base64 encoded string
 * @returns decoded buffer
 */
export declare function base64UrlSafeDecode(input: string): Buffer

/**
 * Base64 encoding (url safe)
 * @param input string or buffer
 * @returns base64 encoded string
 */
export declare function base64UrlSafeEncode(input: string | Buffer): string

export declare function bs58Hash(data: string | Buffer, salt?: string): string

export declare function crc32(input: Uint8Array | string, initialState?: number | undefined | null): number

export declare function crc32Hex(input: Uint8Array | string, initialState?: number | undefined | null): string

/**
 * Derive a new key from a master key.
 * @param keySeed - master key
 * @param subKeyId - sub key id (used verbatim, case-sensitive)
 * @param context - It don't have to be secret and can have a low entropy
 */
export declare function deriveKey(keySeed: string | Buffer, subKeyId: string, context?: string): string

/** Generate Base36-encoded UUID v4 string */
export declare function genBase36UUID(): string

/**
 * Generate a new master key.
 * @returns hex encoded string
 */
export declare function generateKey(): string

/**
 * Computes a fixed-length fingerprint of a string.
 * Suitable for most use cases other than hashing passwords.
 * @param data Message String or Buffer to hash.
 * @param salt 32 bytes hex string. (string length must be 64)
 * @returns hex string
 */
export declare function genericHash(data: string | Buffer, salt?: string): string

/**
 * Generate shorted UUID v4 string
 * @returns shorted UUID v4 string
 */
export declare function genShortUUID(): string

/**
 * Generate UUID v4 string
 * @returns uuid v4
 */
export declare function genUUID(): string

export declare function genUUIDv7(): string

/**
 * Decrypt plain integer with key
 * That is safer alternative to hashids
 * @param {Number} base58 encoded ciphertext
 * @param {String} key
 * @return {String} original integer
 */
export declare function intDecrypt(dataStr: string, keyStr: string): number

/**
 * Encrypt plain integer with key
 * That is safer alternative to hashids
 * @param {Number} data
 * @param {String} key
 * @return {String} base58 encoded ciphertext
 */
export declare function intEncrypt(data: number, keyStr: string): string

export declare const enum JWTAlgorithm {
  /** HMAC using SHA-256 */
  HS256 = 'HS256',
  /** HMAC using SHA-384 */
  HS384 = 'HS384',
  /** HMAC using SHA-512 */
  HS512 = 'HS512',
  /** ECDSA using SHA-256 */
  ES256 = 'ES256',
  /** ECDSA using SHA-384 */
  ES384 = 'ES384',
  /** RSASSA-PKCS1-v1_5 using SHA-256 */
  RS256 = 'RS256',
  /** RSASSA-PKCS1-v1_5 using SHA-384 */
  RS384 = 'RS384',
  /** RSASSA-PKCS1-v1_5 using SHA-512 */
  RS512 = 'RS512',
  /** RSASSA-PSS using SHA-256 */
  PS256 = 'PS256',
  /** RSASSA-PSS using SHA-384 */
  PS384 = 'PS384',
  /** RSASSA-PSS using SHA-512 */
  PS512 = 'PS512',
  /** Edwards-curve Digital Signature Algorithm (EdDSA) */
  EdDSA = 'EdDSA'
}

export declare function jwtDecodeHeader(token: string): JWTHeader

export interface JWTHeader {
  /**
   * The algorithm used
   *
   * Defined in [RFC7515#4.1.1](https://tools.ietf.org/html/rfc7515#section-4.1.1).
   * Default to `HS256`
   */
  algorithm?: JWTAlgorithm
  /**
   * Content type
   *
   * Defined in [RFC7519#5.2](https://tools.ietf.org/html/rfc7519#section-5.2).
   */
  contentType?: string
  /**
   * JSON Key URL
   *
   * Defined in [RFC7515#4.1.2](https://tools.ietf.org/html/rfc7515#section-4.1.2).
   */
  jsonKeyUrl?: string
  /**
   * JSON Web Key
   *
   * Defined in [RFC7515#4.1.3](https://tools.ietf.org/html/rfc7515#section-4.1.3).
   * Key ID
   *
   * Defined in [RFC7515#4.1.4](https://tools.ietf.org/html/rfc7515#section-4.1.4).
   */
  keyId?: string
  /**
   * X.509 URL
   *
   * Defined in [RFC7515#4.1.5](https://tools.ietf.org/html/rfc7515#section-4.1.5).
   */
  x5Url?: string
  /**
   * X.509 certificate chain. A Vec of base64 encoded ASN.1 DER certificates.
   *
   * Defined in [RFC7515#4.1.6](https://tools.ietf.org/html/rfc7515#section-4.1.6).
   */
  x5CertChain?: Array<string>
  /**
   * X.509 SHA1 certificate thumbprint
   *
   * Defined in [RFC7515#4.1.7](https://tools.ietf.org/html/rfc7515#section-4.1.7).
   */
  x5CertThumbprint?: string
  /**
   * X.509 SHA256 certificate thumbprint
   *
   * Defined in [RFC7515#4.1.8](https://tools.ietf.org/html/rfc7515#section-4.1.8).
   *
   * This will be serialized/deserialized as "x5t#S256", as defined by the RFC.
   */
  x5TS256CertThumbprint?: string
}

export declare function jwtSign(claims: { [key: string]: any }, key: string | Uint8Array, header?: JWTHeader | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<string>

export declare function jwtSignSync(claims: { [key: string]: any }, key: string | Uint8Array, header?: JWTHeader | undefined | null): string

export interface JWTValidation {
  /**
   * If it contains a value, the validation will check that the `aud` field is a member of the
   * audience provided and will error otherwise.
   *
   * Defaults to an empty collection.
   */
  aud?: Array<string>
  /**
   * Which claims are required to be present before starting the validation.
   * This does not interact with the various `validate_*`. If you remove `exp` from that list, you still need
   * to set `validate_exp` to `false`.
   * The only value that will be used are "exp", "nbf", "aud", "iss", "sub". Anything else will be ignored.
   *
   * Defaults to `exp`.
   */
  requiredSpecClaims?: Array<string>
  /**
   * Add some leeway (in seconds) to the `exp` and `nbf` validation to
   * account for clock skew.
   *
   * Defaults to `60`.
   */
  leeway?: number
  /**
   * Whether to validate the `exp` field.
   *
   * Defaults to `true`.
   */
  validateExp?: boolean
  /**
   * Whether to validate the `nbf` field.
   *
   * It will return an error if the current timestamp is before the time in the `nbf` field.
   *
   * Defaults to `false`.
   */
  validateNbf?: boolean
  /**
   * If it contains a value, the validation will check that the `sub` field is the same as the
   * one provided and will error otherwise.
   *
   * Turned off by default.
   */
  sub?: string
  /**
   * The algorithm used to verify the signature.
   *
   * Defaults to `HS256`.
   */
  algorithms?: Array<JWTAlgorithm>
  /**
   * If it contains a value, the validation will check that the `iss` field is a member of the
   * iss provided and will error otherwise.
   * Use `set_issuer` to set it
   *
   * Defaults to an empty collection.
   */
  iss?: Array<string>
  /**
   * Whether to validate the JWT signature.
   *
   * Defaults to `true`.
   */
  validateSignature?: boolean
}

export declare function jwtVerify(token: string, key: string | Uint8Array, validation?: JWTValidation | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<{ [key: string]: any }>

export declare function jwtVerifySync(token: string, key: string | Uint8Array, validation?: JWTValidation | undefined | null): { [key: string]: any }

/** Parsed User-Agent struct */
export interface ParsedUa {
  name: string
  category: string
  os: string
  osVersion: string
  browserType: string
  version: string
  vendor: string
}

/**
 * Expand shorted UUID v4 string
 * @param shorted_uuid shorted UUID v4 string
 * @returns standard UUID v4 string
 */
export declare function shortUUIDExpand(shortUuid: string): string

export declare function siphash24(input: Buffer, key: Buffer): Buffer

/**
 * User-Agent Parser
 * @param ua user-agent string
 */
export declare function uaParser(ua: string): ParsedUa

/**
 * Make UUID v4 string shorted
 * @param uuid_v4 UUID v4 string
 * @returns shorted UUID v4 string
 */
export declare function UUIDShorten(uuidV4: string): string

/**
 * Z85 decoding
 * @param input z85 encoded string
 * @returns decoded buffer
 */
export declare function z85Decode(input: string): Buffer

/**
 * Z85 encoding
 * @param input string or buffer
 * @returns z85 encoded string
 */
export declare function z85Encode(input: string | Buffer): string
