defmodule AnkoleWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint for the control-plane web process.

  The endpoint keeps the standard Phoenix request pipeline, but session storage
  is delegated to `AnkoleWeb.SessionCookieStore` so cookie sealing uses the
  shared Ankole kernel crypto format.
  """

  use Phoenix.Endpoint, otp_app: :ankole

  # The session payload is stored in the cookie and sealed with Ankole Kernel
  # AEAD. The browser carries the payload but cannot read or tamper with it.
  @session_options [
    store: AnkoleWeb.SessionCookieStore,
    key: "_ankole_key",
    key_context: "_ankole_key",
    same_site: "Lax",
    max_age: 86_400,
    http_only: true,
    secure: Application.compile_env(:ankole, :secure_cookies, false)
  ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ankole,
    gzip: not code_reloading?,
    only: AnkoleWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ankole
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug AnkoleWeb.Router
end
