defmodule Ankole.Repo.Migrations.CreateActorSessionWorkspaces do
  use Ecto.Migration

  def up do
    create table(:actor_session_workspaces, primary_key: false) do
      add :id, :bigint, primary_key: true

      add :agent_uid,
          references(:principals, column: :uid, type: :text, on_delete: :delete_all),
          null: false

      add :session_id, :text, null: false

      timestamps(type: :utc_datetime_usec)
    end

    execute("""
    ALTER TABLE actor_session_workspaces
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10000)
    """)

    create unique_index(:actor_session_workspaces, [:agent_uid, :session_id],
             name: :actor_session_workspaces_actor_index
           )

    create constraint(:actor_session_workspaces, :actor_session_workspaces_id_range,
             check: "id >= 10000 AND id <= 9007199254740991"
           )

    create constraint(:actor_session_workspaces, :actor_session_workspaces_session_id_present,
             check: "length(btrim(session_id)) > 0"
           )
  end

  def down do
    drop table(:actor_session_workspaces)
  end
end
