defmodule Ankole.Repo.Migrations.ReplaceSubagentEventsWithTurns do
  use Ecto.Migration

  def up do
    # v26.07.7 Subagent runtime state is not an upgrade contract. Discard the
    # old aggregate instead of carrying invalid history into BackgroundAgentJob.
    Enum.each(legacy_runtime_purge_sqls(), &execute/1)

    drop(table(:subagent_delegation_events))

    drop(
      constraint(
        :subagent_delegations,
        :subagent_delegations_source_delegation_id_fkey
      )
    )

    execute("""
    ALTER TABLE subagent_delegations
      ALTER COLUMN source_delegation_id TYPE bigint USING NULL::bigint,
      ALTER COLUMN id TYPE bigint USING NULL::bigint,
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)
    """)

    create(
      constraint(:subagent_delegations, :subagent_delegations_id_range,
        check: "id >= 1000 AND id <= 9007199254740991"
      )
    )

    execute("""
    ALTER TABLE subagent_delegations
      ADD CONSTRAINT subagent_delegations_source_delegation_id_fkey
      FOREIGN KEY (source_delegation_id)
      REFERENCES subagent_delegations(id)
      ON DELETE RESTRICT
    """)

    create table(:subagent_delegation_turns, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :delegation_id,
          references(:subagent_delegations, type: :bigint, on_delete: :delete_all),
          null: false

      add :attempt, :integer, null: false
      add :runtime_thread_id, :text, null: false
      add :runtime_turn_id, :text, null: false
      add :kind, :text, null: false, default: "agent"
      add :status, :text, null: false
      add :revision, :bigint, null: false
      add :trajectory, :map, null: false
      add :usage, :map, null: false, default: %{}
      add :error, :map, null: false, default: %{}
      add :started_at, :utc_datetime_usec, null: false
      add :last_activity_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    create unique_index(:subagent_delegation_turns, [:delegation_id, :runtime_turn_id],
             name: :subagent_delegation_turns_runtime_turn_index
           )

    create index(:subagent_delegation_turns, [:delegation_id, :attempt, :started_at, :id],
             name: :subagent_delegation_turns_timeline_index
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_attempt_positive,
             check: "attempt > 0"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_revision_nonnegative,
             check: "revision >= 0"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_kind_check,
             check: "kind IN ('agent', 'compaction')"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_status_check,
             check: "status IN ('in_progress', 'completed', 'failed', 'interrupted')"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_trajectory_check,
             check: """
             jsonb_typeof(trajectory) = 'object' AND
             trajectory @> '{"format":"ankole_chatml","version":1}'::jsonb AND
             jsonb_typeof(trajectory->'messages') = 'array' AND
             jsonb_array_length(jsonb_path_query_array(trajectory, '$.messages[*].role')) =
               jsonb_array_length(trajectory->'messages') AND
             jsonb_path_query_array(trajectory, '$.messages[*].role') <@
               '["user","developer","assistant","tool"]'::jsonb
             """
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_trajectory_bytes,
             check: "octet_length(trajectory::text) <= 524288"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_usage_object,
             check: "jsonb_typeof(usage) = 'object'"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_error_object,
             check: "jsonb_typeof(error) = 'object'"
           )

    create constraint(:subagent_delegation_turns, :subagent_delegation_turns_completion_check,
             check: """
             (status = 'in_progress' AND completed_at IS NULL) OR
             (status IN ('completed', 'failed', 'interrupted') AND completed_at IS NOT NULL)
             """
           )
  end

  def down do
    raise "BackgroundAgentJob cutover cannot be downgraded: v26.07.7 Subagent runtime state is intentionally discarded"
  end

  @doc false
  def legacy_runtime_purge_sqls do
    legacy_actor_events = """
    SELECT id
    FROM actor_events
    WHERE type LIKE 'subagent.delegation.%'
       OR source_event_id LIKE 'subagent_delegation:%'
       OR session_id LIKE 'subagent:%'
    """

    [
      """
      DELETE FROM actor_event_deliveries
      WHERE session_id LIKE 'subagent:%'
         OR actor_event_id IN (#{legacy_actor_events})
         OR actor_event_id_fence IN (#{legacy_actor_events})
      """,
      "DELETE FROM actor_session_activations WHERE session_id LIKE 'subagent:%'",
      "DELETE FROM actor_session_worker_assignments WHERE session_id LIKE 'subagent:%'",
      "DELETE FROM actor_scheduled_events WHERE session_id LIKE 'subagent:%'",
      "DELETE FROM actor_cron_schedules WHERE session_id LIKE 'subagent:%'",
      "DELETE FROM signal_gateway_inbound_batches WHERE session_id LIKE 'subagent:%'",
      "DELETE FROM ai_gateway_conversations WHERE conversation_key LIKE 'subagent:%'",
      """
      DELETE FROM actor_events
      WHERE type LIKE 'subagent.delegation.%'
         OR source_event_id LIKE 'subagent_delegation:%'
         OR session_id LIKE 'subagent:%'
      """,
      "DELETE FROM subagent_delegations"
    ]
  end
end
