defmodule Ankole.Repo.Migrations.CreateBrainV3 do
  @moduledoc false

  use Ecto.Migration

  # BrainV3 instance knowledge space. The authoritative field list and the
  # database rules live in docs/design-docs/BrainV3.md ("准备表" and the
  # schema-pack state tables). Every UUID primary key is generated by the
  # application through Ankole.Ecto.UUIDv7; the database never generates a
  # random UUID for these tables.
  def up do
    execute("CREATE EXTENSION IF NOT EXISTS vector")
    execute("CREATE EXTENSION IF NOT EXISTS pg_search")
    execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    create_schema_pack_tables()
    create_sources()
    create_objects()
    create_object_versions()
    create_chunks()
    create_claims()
    create_timelines()
    create_links()
    create_tags()
    create_slug_aliases()
    create_object_aliases()
    create_take_domain_assignments()
    create_contradictions()
    create_schema_suggestions()
    create_search_indexes()

    # Data backfills run through repo() immediately; the queued DDL above
    # must exist first.
    flush()

    insert_brain_system_principal()
    backfill_canonical_principal_objects()
  end

  def down do
    drop table(:brain_schema_suggestions)
    drop table(:brain_contradictions)
    drop table(:brain_take_domain_assignments)
    drop table(:brain_object_aliases)
    drop table(:brain_slug_aliases)
    drop table(:brain_tags)
    drop table(:brain_links)
    drop table(:brain_timelines)
    drop table(:brain_claims)
    drop table(:brain_chunks)
    drop table(:brain_object_versions)
    drop table(:brain_objects)
    drop table(:brain_sources)
    drop table(:brain_schema_calibration_domains)
    drop table(:brain_schema_link_types)
    drop table(:brain_schema_types)
    drop table(:brain_schema_packs)

    execute("DELETE FROM principals WHERE uid = 'brain' AND type = 'system'")

    execute("DROP EXTENSION IF EXISTS pg_search")
    execute("DROP EXTENSION IF EXISTS vector")
    execute("DROP EXTENSION IF EXISTS pg_trgm")
  end

  # ── Schema pack state ────────────────────────────────────────────

  defp create_schema_pack_tables do
    create table(:brain_schema_packs, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :name, :text, null: false
      add :version, :text, null: false
      add :content_hash, :text, null: false
      add :manifest, :map, null: false
      add :installed_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_schema_packs, [:name], name: :brain_schema_packs_name_key)

    create constraint(:brain_schema_packs, :brain_schema_packs_manifest_object,
             check: "jsonb_typeof(manifest) = 'object'"
           )

    comment_table(:brain_schema_packs, "Schema pack installation records for this instance.")

    create table(:brain_schema_types, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :name, :text, null: false
      add :primitive, :text, null: false
      add :slug_prefix, :text, null: false
      add :subtypes, :map, null: false, default: fragment("'[]'::jsonb")
      add :extractable, :boolean, null: false, default: false
      add :expert_routing, :boolean, null: false, default: false

      add :pack_name,
          references(:brain_schema_packs, column: :name, type: :text, on_delete: :restrict),
          null: false

      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_schema_types, [:name], name: :brain_schema_types_name_key)

    create unique_index(:brain_schema_types, [:slug_prefix], name: :brain_schema_types_prefix_key)

    create constraint(:brain_schema_types, :brain_schema_types_primitive_allowed,
             check: "primitive IN ('entity', 'media', 'temporal', 'annotation', 'concept')"
           )

    comment_table(:brain_schema_types, "Type registry of the instance ontology.")

    create table(:brain_schema_link_types, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :name, :text, null: false
      add :inverse, :text

      add :pack_name,
          references(:brain_schema_packs, column: :name, type: :text, on_delete: :restrict),
          null: false

      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_schema_link_types, [:name],
             name: :brain_schema_link_types_name_key
           )

    comment_table(:brain_schema_link_types, "Relation predicate vocabulary.")

    create table(:brain_schema_calibration_domains, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :name, :text, null: false
      add :aggregator, :text, null: false

      add :pack_name,
          references(:brain_schema_packs, column: :name, type: :text, on_delete: :restrict),
          null: false

      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_schema_calibration_domains, [:name],
             name: :brain_schema_calibration_domains_name_key
           )

    comment_table(:brain_schema_calibration_domains, "Take calibration domain registry.")
  end

  # ── Sources ──────────────────────────────────────────────────────

  defp create_sources do
    create table(:brain_sources, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :upstream_id, :text, null: false
      add :kind, :text, null: false
      add :name, :text, null: false
      add :default_audience_scope, :text
      add :config, :map, null: false, default: %{}
      add :upstream_revision, :text
      add :last_sync_at, :utc_datetime_usec
      add :archived_at, :utc_datetime_usec
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_sources, [:kind, :upstream_id],
             name: :brain_sources_kind_upstream_key
           )

    execute("""
    CREATE INDEX brain_sources_active_idx
    ON brain_sources (updated_at DESC)
    WHERE archived_at IS NULL
    """)

    create constraint(:brain_sources, :brain_sources_upstream_present,
             check: "btrim(upstream_id) <> ''"
           )

    create constraint(:brain_sources, :brain_sources_kind_present, check: "btrim(kind) <> ''")
    create constraint(:brain_sources, :brain_sources_name_present, check: "btrim(name) <> ''")

    create constraint(:brain_sources, :brain_sources_default_scope_format,
             check:
               "default_audience_scope IS NULL OR #{scope_shape_sql("default_audience_scope")}"
           )

    create constraint(:brain_sources, :brain_sources_config_object,
             check: "jsonb_typeof(config) = 'object'"
           )

    comment_table(:brain_sources, "Upstream learning sources registered for this instance.")
  end

  # ── Objects ──────────────────────────────────────────────────────

  defp create_objects do
    create table(:brain_objects, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :slug, :text, null: false
      add :type, :text, null: false
      add :subtype, :text
      add :title, :text, null: false
      add :body, :text, null: false, default: ""
      add :meta, :map, null: false, default: %{}
      add :effective_date, :date
      add :content_hash, :text
      add :chunking_signature, :text
      add :emotional_weight, :float, null: false, default: 0.0
      add :emotional_weight_recomputed_at, :utc_datetime_usec
      add :salience_touched_at, :utc_datetime_usec
      add :last_retrieved_at, :utc_datetime_usec
      add :links_extracted_at, :utc_datetime_usec
      add :deleted_at, :utc_datetime_usec
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_objects, [:slug], name: :brain_objects_slug_key)

    execute("""
    CREATE INDEX brain_objects_slug_prefix_idx
    ON brain_objects (slug text_pattern_ops)
    """)

    create index(:brain_objects, [:type], name: :brain_objects_type_idx)

    execute("CREATE INDEX brain_objects_updated_idx ON brain_objects (updated_at DESC)")

    execute("""
    CREATE INDEX brain_objects_effective_date_idx
    ON brain_objects (effective_date DESC)
    WHERE deleted_at IS NULL AND effective_date IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_objects_deleted_idx
    ON brain_objects (deleted_at)
    WHERE deleted_at IS NOT NULL
    """)

    create index(:brain_objects, [:last_retrieved_at], name: :brain_objects_last_retrieved_idx)

    execute("""
    CREATE INDEX brain_objects_title_trgm_idx
    ON brain_objects
    USING gin (title gin_trgm_ops)
    """)

    create constraint(:brain_objects, :brain_objects_slug_present, check: "btrim(slug) <> ''")
    create constraint(:brain_objects, :brain_objects_type_present, check: "btrim(type) <> ''")
    create constraint(:brain_objects, :brain_objects_title_present, check: "btrim(title) <> ''")

    create constraint(:brain_objects, :brain_objects_meta_object,
             check: "jsonb_typeof(meta) = 'object'"
           )

    create constraint(:brain_objects, :brain_objects_emotional_weight_range,
             check: "emotional_weight >= 0.0 AND emotional_weight <= 1.0"
           )

    comment_table(:brain_objects, "Current pages of the instance knowledge space.")
  end

  defp create_object_versions do
    create table(:brain_object_versions, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :object_id,
          references(:brain_objects, column: :id, type: :uuid, on_delete: :delete_all),
          null: false

      add :author_uid, references(:principals, column: :uid, type: :text, on_delete: :nilify_all)

      add :body, :text, null: false
      add :meta, :map, null: false, default: %{}
      add :snapshot_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    execute("""
    CREATE INDEX brain_object_versions_object_idx
    ON brain_object_versions (object_id, snapshot_at DESC)
    """)

    create constraint(:brain_object_versions, :brain_object_versions_meta_object,
             check: "jsonb_typeof(meta) = 'object'"
           )

    comment_table(:brain_object_versions, "Body history snapshots taken before object updates.")
  end

  defp create_chunks do
    create table(:brain_chunks, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :object_id,
          references(:brain_objects, column: :id, type: :uuid, on_delete: :delete_all),
          null: false

      add :chunk_index, :integer, null: false
      add :content_kind, :text, null: false, default: "body"
      add :audience_scope, :text, null: false
      add :chunk_text, :text, null: false
      add :token_count, :integer, null: false
      add :embedding, :"vector(4096)"
      add :embedding_signature, :text
      add :embedding_error, :text
      add :embedded_at, :utc_datetime_usec
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_chunks, [:object_id, :chunk_index],
             name: :brain_chunks_object_position_key
           )

    create index(:brain_chunks, [:object_id, :content_kind, :chunk_index],
             name: :brain_chunks_object_content_kind_idx
           )

    execute("""
    CREATE INDEX brain_chunks_embedding_hnsw_idx
    ON brain_chunks USING hnsw
      ((subvector(embedding, 1, 4000)::halfvec(4000)) halfvec_cosine_ops)
    WHERE embedding IS NOT NULL
    """)

    create constraint(:brain_chunks, :brain_chunks_index_nonnegative, check: "chunk_index >= 0")

    create constraint(:brain_chunks, :brain_chunks_content_kind_values,
             check: "content_kind IN ('body', 'timeline')"
           )

    create constraint(:brain_chunks, :brain_chunks_token_count_nonnegative,
             check: "token_count >= 0"
           )

    create constraint(:brain_chunks, :brain_chunks_audience_scope_shape,
             check: scope_shape_sql("audience_scope")
           )

    create constraint(:brain_chunks, :brain_chunks_embedding_state, check: embedding_state_sql())

    comment_table(:brain_chunks, "Rebuildable retrieval projection of current object content.")
  end

  # ── Claims ───────────────────────────────────────────────────────

  defp create_claims do
    create table(:brain_claims, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :author_uid, references(:principals, column: :uid, type: :text, on_delete: :nilify_all)
      add :claim_type, :text, null: false

      # Slug is a mutable key: schema promotion retypes objects and migrates
      # their slug prefix, so every slug reference (here and in the tables
      # below) follows the rename with ON UPDATE CASCADE.
      add :object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :signal_gateway_channel_id,
          references(:signal_gateway_channels, column: :id, type: :text, on_delete: :restrict)

      add :claim, :text, null: false
      add :kind, :text, null: false
      add :holder, :text, null: false
      add :audience_scope, :text, null: false

      # Fact fields (GBrain facts); all NULL for takes.
      add :notability, :text
      add :context, :text
      add :valid_from, :utc_datetime_usec
      add :valid_until, :utc_datetime_usec
      add :expired_at, :utc_datetime_usec
      add :consolidated_at, :utc_datetime_usec
      add :consolidated_into, references(:brain_claims, column: :id, type: :uuid)
      add :confidence, :float
      add :provenance_session, :text
      add :claim_metric, :text
      add :claim_value, :float
      add :claim_unit, :text
      add :claim_period, :text
      add :event_type, :text
      add :dimension, :text
      add :value, :text
      add :value_hash, :text
      add :dim_status, :text

      # Take fields (GBrain takes); all NULL for facts.
      add :weight, :float
      add :since_date, :text
      add :until_date, :text
      add :active, :boolean
      add :graded_quality, :text
      add :graded_confidence, :float
      add :graded_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec
      add :resolved_outcome, :boolean
      add :resolved_quality, :text
      add :resolved_value, :float
      add :resolved_unit, :text
      add :resolution_provenance, :text
      add :resolved_by, :text

      # Shared fields.
      add :superseded_by, references(:brain_claims, column: :id, type: :uuid)
      add :provenance, :text, null: false
      add :embedding, :"vector(4096)"
      add :embedding_signature, :text
      add :embedding_error, :text
      add :embedded_at, :utc_datetime_usec
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    execute("""
    CREATE INDEX brain_claims_object_current_idx
    ON brain_claims (object_slug, holder, valid_from DESC)
    WHERE claim_type = 'fact' AND expired_at IS NULL AND object_slug IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_claims_channel_current_idx
    ON brain_claims (signal_gateway_channel_id, holder, valid_from DESC)
    WHERE claim_type = 'fact' AND expired_at IS NULL AND signal_gateway_channel_id IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_claims_take_active_idx
    ON brain_claims (holder, kind, weight DESC)
    WHERE claim_type = 'take' AND active = true
    """)

    execute("""
    CREATE INDEX brain_claims_provenance_session_idx
    ON brain_claims (provenance_session, created_at DESC)
    WHERE claim_type = 'fact' AND expired_at IS NULL AND provenance_session IS NOT NULL
    """)

    # One extraction terminal per slice version token: a concurrent rerun of
    # the same slice fails its commit instead of double-writing memory.
    execute("""
    CREATE UNIQUE INDEX brain_claims_extraction_terminal_key
    ON brain_claims (signal_gateway_channel_id, provenance_session)
    WHERE provenance LIKE 'ankole-brain-internal:%' AND provenance_session IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_claims_metric_idx
    ON brain_claims (object_slug, claim_metric, valid_from DESC)
    WHERE claim_type = 'fact' AND claim_metric IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_claims_scorecard_idx
    ON brain_claims (holder, kind, resolved_quality)
    WHERE claim_type = 'take' AND resolved_quality IS NOT NULL
    """)

    create index(:brain_claims, [:audience_scope], name: :brain_claims_audience_scope_idx)

    execute("""
    CREATE INDEX brain_claims_author_idx
    ON brain_claims (author_uid)
    WHERE author_uid IS NOT NULL
    """)

    execute("""
    CREATE UNIQUE INDEX brain_claims_object_dimension_key
    ON brain_claims (object_slug, dimension, value_hash, provenance)
    WHERE claim_type = 'fact' AND object_slug IS NOT NULL AND dimension IS NOT NULL
    """)

    execute("""
    CREATE UNIQUE INDEX brain_claims_channel_dimension_key
    ON brain_claims (signal_gateway_channel_id, dimension, value_hash, provenance)
    WHERE claim_type = 'fact' AND signal_gateway_channel_id IS NOT NULL AND dimension IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_claims_embedding_hnsw_idx
    ON brain_claims USING hnsw
      ((subvector(embedding, 1, 4000)::halfvec(4000)) halfvec_cosine_ops)
    WHERE embedding IS NOT NULL
      AND ((claim_type = 'fact' AND expired_at IS NULL)
        OR (claim_type = 'take' AND active = true))
    """)

    create constraint(:brain_claims, :brain_claims_type_values,
             check: "claim_type IN ('fact', 'take')"
           )

    create constraint(:brain_claims, :brain_claims_parent_xor,
             check: "num_nonnulls(object_slug, signal_gateway_channel_id) = 1"
           )

    create constraint(:brain_claims, :brain_claims_required_text_present,
             check:
               "btrim(claim) <> '' AND btrim(kind) <> '' AND btrim(holder) <> '' AND btrim(provenance) <> ''"
           )

    create constraint(:brain_claims, :brain_claims_audience_scope_shape,
             check: scope_shape_sql("audience_scope")
           )

    create constraint(:brain_claims, :brain_claims_grade_shape,
             check: """
             (graded_quality IS NULL OR graded_quality IN ('correct', 'incorrect', 'partial', 'unresolvable'))
             AND (graded_confidence IS NULL OR (graded_confidence >= 0.0 AND graded_confidence <= 1.0))
             """
           )

    create constraint(:brain_claims, :brain_claims_resolution_quality_values,
             check:
               "resolved_quality IS NULL OR resolved_quality IN ('correct', 'incorrect', 'partial', 'unresolvable')"
           )

    create constraint(:brain_claims, :brain_claims_resolution_consistency,
             check: """
             (resolved_quality IS NULL AND resolved_outcome IS NULL)
             OR (resolved_quality IN ('correct', 'incorrect') AND resolved_outcome IS NOT NULL)
             OR (resolved_quality IN ('partial', 'unresolvable') AND resolved_outcome IS NULL)
             """
           )

    create constraint(:brain_claims, :brain_claims_type_shape, check: claim_type_shape_sql())

    create constraint(:brain_claims, :brain_claims_embedding_state, check: embedding_state_sql())

    comment_table(:brain_claims, "Atomic facts and calibratable takes in one physical table.")
  end

  # ── Timelines, links, tags, aliases ─────────────────────────────

  defp create_timelines do
    create table(:brain_timelines, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :author_uid, references(:principals, column: :uid, type: :text, on_delete: :nilify_all)
      add :date, :date, null: false
      add :provenance, :text, null: false
      add :summary, :text, null: false
      add :detail, :text, null: false, default: ""

      add :event_object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :audience_scope, :text, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_timelines, [:object_slug, :date, :summary, :provenance],
             name: :brain_timelines_dedup_key
           )

    execute("""
    CREATE UNIQUE INDEX brain_timelines_event_dedup_key
    ON brain_timelines (event_object_slug, date)
    WHERE event_object_slug IS NOT NULL
    """)

    execute("""
    CREATE INDEX brain_timelines_object_idx ON brain_timelines (object_slug, date DESC)
    """)

    execute("CREATE INDEX brain_timelines_date_idx ON brain_timelines (date DESC)")

    create constraint(:brain_timelines, :brain_timelines_provenance_present,
             check: "btrim(provenance) <> ''"
           )

    create constraint(:brain_timelines, :brain_timelines_summary_present,
             check: "btrim(summary) <> ''"
           )

    create constraint(:brain_timelines, :brain_timelines_audience_scope_shape,
             check: scope_shape_sql("audience_scope")
           )

    comment_table(:brain_timelines, "Structured timeline events attached to objects.")
  end

  defp create_links do
    create table(:brain_links, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :from_object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :to_object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :link_type, :text, null: false, default: ""
      add :context, :text, null: false, default: ""
      add :link_source, :text
      add :link_kind, :text

      add :origin_object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :origin_field, :text
      add :resolution_type, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    execute("""
    CREATE UNIQUE INDEX brain_links_dedup_key
    ON brain_links (from_object_slug, to_object_slug, link_type, link_source, origin_object_slug)
    NULLS NOT DISTINCT
    """)

    create index(:brain_links, [:from_object_slug], name: :brain_links_from_idx)
    create index(:brain_links, [:to_object_slug], name: :brain_links_to_idx)
    create index(:brain_links, [:link_source], name: :brain_links_source_idx)
    create index(:brain_links, [:origin_object_slug], name: :brain_links_origin_idx)

    create constraint(:brain_links, :brain_links_source_shape,
             check:
               "link_source IS NULL OR (link_source ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(link_source) <= 64)"
           )

    create constraint(:brain_links, :brain_links_kind_values,
             check: "link_kind IS NULL OR link_kind IN ('plain', 'typed_ner')"
           )

    create constraint(:brain_links, :brain_links_resolution_values,
             check: "resolution_type IS NULL OR resolution_type IN ('qualified', 'unqualified')"
           )

    comment_table(:brain_links, "Directed relation edges between objects.")
  end

  defp create_tags do
    create table(:brain_tags, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :tag, :text, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_tags, [:object_slug, :tag], name: :brain_tags_object_tag_key)
    create index(:brain_tags, [:tag], name: :brain_tags_tag_idx)

    create constraint(:brain_tags, :brain_tags_tag_present, check: "btrim(tag) <> ''")

    comment_table(:brain_tags, "Queryable object tags as independent rows.")
  end

  defp create_slug_aliases do
    create table(:brain_slug_aliases, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :alias_slug, :text, null: false

      add :canonical_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :notes, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_slug_aliases, [:alias_slug], name: :brain_slug_aliases_alias_key)

    create index(:brain_slug_aliases, [:canonical_slug], name: :brain_slug_aliases_canonical_idx)

    create constraint(:brain_slug_aliases, :brain_slug_aliases_no_self,
             check: "alias_slug <> canonical_slug"
           )

    comment_table(:brain_slug_aliases, "Stable redirects from retired slugs to current slugs.")
  end

  defp create_object_aliases do
    create table(:brain_object_aliases, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :alias_norm, :text, null: false

      add :object_slug,
          references(:brain_objects,
            column: :slug,
            type: :text,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_object_aliases, [:alias_norm, :object_slug],
             name: :brain_object_aliases_dedup_key
           )

    create index(:brain_object_aliases, [:alias_norm], name: :brain_object_aliases_lookup_idx)
    create index(:brain_object_aliases, [:object_slug], name: :brain_object_aliases_object_idx)

    create constraint(:brain_object_aliases, :brain_object_aliases_alias_present,
             check: "btrim(alias_norm) <> ''"
           )

    comment_table(:brain_object_aliases, "Normalized natural-language aliases per object.")
  end

  defp create_take_domain_assignments do
    create table(:brain_take_domain_assignments, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :take_claim_id,
          references(:brain_claims, column: :id, type: :uuid, on_delete: :delete_all),
          null: false

      add :domain, :text, null: false
      add :pack, :text, null: false
      add :assignment_provenance, :text
      add :confidence, :float, null: false, default: 1.0
      add :assigned_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:brain_take_domain_assignments, [:take_claim_id, :domain],
             name: :brain_take_domain_assignments_key
           )

    create index(:brain_take_domain_assignments, [:domain, :take_claim_id],
             name: :brain_take_domain_assignments_domain_idx
           )

    create constraint(
             :brain_take_domain_assignments,
             :brain_take_domain_assignments_confidence_range,
             check: "confidence >= 0.0 AND confidence <= 1.0"
           )

    comment_table(:brain_take_domain_assignments, "Analysis-domain assignments for takes.")
  end

  defp create_contradictions do
    create table(:brain_contradictions, primary_key: false) do
      add :id, :uuid, primary_key: true

      add :a_claim_id,
          references(:brain_claims, column: :id, type: :uuid, on_delete: :delete_all),
          null: false

      add :b_claim_id,
          references(:brain_claims, column: :id, type: :uuid, on_delete: :delete_all),
          null: false

      add :verdict, :text, null: false
      add :axis, :text, null: false, default: ""
      add :severity, :text, null: false
      add :confidence, :float, null: false
      add :status, :text, null: false, default: "open"
      add :resolution_note, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :decided_at, :utc_datetime_usec
    end

    create unique_index(:brain_contradictions, [:a_claim_id, :b_claim_id],
             name: :brain_contradictions_pair_key
           )

    execute("""
    CREATE INDEX brain_contradictions_triage_idx
    ON brain_contradictions (status, severity, created_at DESC)
    """)

    create constraint(:brain_contradictions, :brain_contradictions_severity_values,
             check: "severity IN ('info', 'low', 'medium', 'high')"
           )

    create constraint(:brain_contradictions, :brain_contradictions_status_values,
             check: "status IN ('open', 'resolved', 'dismissed')"
           )

    create constraint(:brain_contradictions, :brain_contradictions_confidence_range,
             check: "confidence >= 0.0 AND confidence <= 1.0"
           )

    comment_table(:brain_contradictions, "Contradiction probe findings cache.")
  end

  defp create_schema_suggestions do
    create table(:brain_schema_suggestions, primary_key: false) do
      add :id, :uuid, primary_key: true
      add :kind, :text, null: false
      add :term, :text, null: false
      add :target_type, :text
      add :evidence_count, :integer, null: false
      add :rationale, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :decided_by, references(:principals, column: :uid, type: :text, on_delete: :nilify_all)
      add :decided_at, :utc_datetime_usec
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    execute("""
    CREATE UNIQUE INDEX brain_schema_suggestions_pending_key
    ON brain_schema_suggestions (term, kind)
    WHERE status = 'pending'
    """)

    create constraint(:brain_schema_suggestions, :brain_schema_suggestions_kind_values,
             check: "kind IN ('new_type', 'new_subtype', 'alias')"
           )

    create constraint(:brain_schema_suggestions, :brain_schema_suggestions_status_values,
             check: "status IN ('pending', 'approved', 'rejected')"
           )

    comment_table(:brain_schema_suggestions, "Vocabulary promotion suggestion queue.")
  end

  # ── Search indexes ───────────────────────────────────────────────

  # The initial migration always builds with the default icu tokenizer; a
  # brain.search_tokenizer change rebuilds these two recoverable indexes at
  # runtime without touching the base tables.
  defp create_search_indexes do
    execute("""
    CREATE INDEX brain_chunks_bm25_idx
    ON brain_chunks
    USING bm25 (id, (chunk_text::pdb.icu))
    WITH (key_field='id')
    """)

    execute("""
    CREATE INDEX brain_claims_bm25_idx
    ON brain_claims
    USING bm25 (id, (claim::pdb.icu))
    WITH (key_field='id')
    """)
  end

  # ── Data backfills ───────────────────────────────────────────────

  # Brain owns instance-global model calls (embedding, extraction, dreaming)
  # and needs an accountable system Principal as their AIGateway subject.
  # Principal UIDs are caller-chosen text, so a human or agent may already
  # occupy `brain`; silently reusing it would misattribute every Brain model
  # call, its cost, and its audit trail to that identity. The upgrade fails
  # loudly instead and tells the operator to rename the existing principal.
  defp insert_brain_system_principal do
    %{rows: rows} =
      repo().query!("SELECT type FROM principals WHERE uid = 'brain'", [])

    case rows do
      [[type]] when type != "system" ->
        raise """
        principal uid 'brain' already exists with type '#{type}'. BrainV3 \
        reserves this uid for its system subject. Rename or delete that \
        principal, then run the upgrade again.\
        """

      _absent_or_system ->
        repo().query!(
          """
          INSERT INTO principals (uid, type, status, display_name, inserted_at, updated_at)
          VALUES ('brain', 'system', 'active', 'Brain', now(), now())
          ON CONFLICT (uid) DO NOTHING
          """,
          []
        )
    end
  end

  # Every human and agent Principal owns one canonical Object. Later Principal
  # and Agent creation transactions keep this invariant; this backfill covers
  # rows that exist before BrainV3.
  defp backfill_canonical_principal_objects do
    rows =
      repo().query!(
        """
        SELECT uid, type, display_name FROM principals
        WHERE type IN ('human', 'agent')
        """,
        []
      )

    Enum.each(rows.rows, fn [uid, type, display_name] ->
      slug =
        case type do
          "human" -> "people/#{uid}"
          "agent" -> "agents/#{uid}"
        end

      object_type =
        case type do
          "human" -> "person"
          "agent" -> "agent"
        end

      repo().query!(
        """
        INSERT INTO brain_objects (id, slug, type, subtype, title, body, meta, created_at, updated_at)
        VALUES ($1, $2, $3, 'internal', $4, '', '{}'::jsonb, now(), now())
        ON CONFLICT (slug) DO NOTHING
        """,
        [
          Ecto.UUID.dump!(Ankole.Ecto.UUIDv7.autogenerate()),
          slug,
          object_type,
          display_name || uid
        ]
      )
    end)
  end

  # ── SQL helpers ──────────────────────────────────────────────────

  defp scope_shape_sql(column) do
    "#{column} ~ '^(world|group:.+|principal:.+)$'"
  end

  defp embedding_state_sql do
    """
    (embedding IS NULL AND embedding_signature IS NULL AND embedding_error IS NULL AND embedded_at IS NULL)
    OR (embedding IS NOT NULL AND embedding_signature IS NOT NULL AND embedded_at IS NOT NULL AND embedding_error IS NULL)
    OR (embedding IS NULL AND embedding_signature IS NOT NULL AND embedding_error IS NOT NULL AND embedded_at IS NULL)
    """
  end

  defp claim_type_shape_sql do
    """
    (
      claim_type = 'fact'
      AND kind IN ('event', 'preference', 'commitment', 'belief', 'fact')
      AND notability IN ('high', 'medium', 'low')
      AND valid_from IS NOT NULL
      AND confidence IS NOT NULL AND confidence >= 0.0 AND confidence <= 1.0
      AND num_nonnulls(
        weight, since_date, until_date, active, graded_quality, graded_confidence,
        graded_at, resolved_at, resolved_outcome, resolved_quality, resolved_value,
        resolved_unit, resolution_provenance, resolved_by
      ) = 0
    )
    OR (
      claim_type = 'take'
      AND weight IS NOT NULL AND weight >= 0.0 AND weight <= 1.0
      AND active IS NOT NULL
      AND num_nonnulls(
        notability, context, valid_from, valid_until, expired_at, consolidated_at,
        consolidated_into, confidence, provenance_session, claim_metric, claim_value,
        claim_unit, claim_period, event_type, dimension, value, value_hash, dim_status
      ) = 0
    )
    """
  end

  defp comment_table(table, comment) do
    execute("COMMENT ON TABLE #{identifier(table)} IS #{literal(comment)}")
  end

  defp identifier(value), do: "\"" <> String.replace(to_string(value), "\"", "\"\"") <> "\""
  defp literal(value), do: "'" <> String.replace(value, "'", "''") <> "'"
end
