defmodule Ankole.Repo.Migrations.CreateAutomationJobs do
  use Ecto.Migration

  def up do
    create table(:automation_jobs, primary_key: false) do
      add :id, :bigint, primary_key: true

      add :agent_uid,
          references(:principals, column: :uid, type: :text, on_delete: :delete_all),
          null: false

      add :owner_session_id, :text, null: false
      add :source_actor_event_id, references(:actor_events, type: :uuid, on_delete: :nilify_all)
      add :source_entry_id, :text
      add :source_provenance, :map, null: false, default: %{}
      add :reply_route, :map, null: false, default: %{}
      add :directory_path, :text, null: false
      add :label, :text, null: false
      add :wake_on_failure, :boolean, null: false, default: false
      add :status, :text, null: false, default: "active"
      add :expires_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    execute("""
    ALTER TABLE automation_jobs
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)
    """)

    create table(:automation_job_runs, primary_key: false) do
      add :id, :bigint, primary_key: true

      add :automation_job_id,
          references(:automation_jobs, type: :bigint, on_delete: :delete_all),
          null: false

      add :event, :map, null: false
      add :status, :text, null: false, default: "queued"
      add :attempts, :integer, null: false, default: 0
      add :attempt_id, :uuid
      add :oban_job_id, :bigint
      add :started_at, :utc_datetime_usec
      add :last_attempt_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :exit_code, :integer
      add :error, :text
      add :stdout, :text, null: false, default: ""
      add :stderr, :text, null: false, default: ""
      add :stdout_truncated, :boolean, null: false, default: false
      add :stderr_truncated, :boolean, null: false, default: false

      timestamps(type: :utc_datetime_usec)
    end

    execute("""
    ALTER TABLE automation_job_runs
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)
    """)

    alter table(:actor_scheduled_events) do
      add :automation_job_id,
          references(:automation_jobs, type: :bigint, on_delete: :restrict)

      add :automation_job_run_id,
          references(:automation_job_runs, type: :bigint, on_delete: :nilify_all)
    end

    alter table(:actor_cron_schedules) do
      add :automation_job_id,
          references(:automation_jobs, type: :bigint, on_delete: :restrict)
    end

    alter table(:signal_gateway_webhook_endpoints) do
      add :automation_job_id,
          references(:automation_jobs, type: :bigint, on_delete: :restrict)
    end

    create index(:automation_jobs, [:agent_uid, :owner_session_id, :status, :id],
             name: :automation_jobs_owner_status_index
           )

    create index(:automation_job_runs, [:automation_job_id, :inserted_at, :id],
             name: :automation_job_runs_timeline_index
           )

    create index(:automation_job_runs, [:status, :inserted_at],
             name: :automation_job_runs_status_index,
             where: "status IN ('queued', 'running')"
           )

    create index(:actor_scheduled_events, [:automation_job_id],
             name: :actor_scheduled_events_automation_job_index,
             where: "automation_job_id IS NOT NULL"
           )

    create index(:actor_scheduled_events, [:automation_job_run_id],
             name: :actor_scheduled_events_automation_job_run_index,
             where: "automation_job_run_id IS NOT NULL"
           )

    create index(:actor_cron_schedules, [:automation_job_id],
             name: :actor_cron_schedules_automation_job_index,
             where: "automation_job_id IS NOT NULL"
           )

    create index(:signal_gateway_webhook_endpoints, [:automation_job_id],
             name: :signal_gateway_webhook_endpoints_automation_job_index,
             where: "automation_job_id IS NOT NULL"
           )

    create constraint(:automation_jobs, :automation_jobs_id_range,
             check: "id >= 1000 AND id <= 9007199254740991"
           )

    create constraint(:automation_jobs, :automation_jobs_status_check,
             check: "status IN ('active', 'cancelled', 'expired')"
           )

    create constraint(:automation_jobs, :automation_jobs_owner_session_present,
             check: "length(btrim(owner_session_id)) > 0"
           )

    create constraint(:automation_jobs, :automation_jobs_directory_path_present,
             check: "length(btrim(directory_path)) > 0 AND length(directory_path) <= 4096"
           )

    create constraint(:automation_jobs, :automation_jobs_label_present,
             check: "length(btrim(label)) > 0 AND length(label) <= 500"
           )

    create constraint(:automation_jobs, :automation_jobs_source_provenance_object,
             check: "jsonb_typeof(source_provenance) = 'object'"
           )

    create constraint(:automation_jobs, :automation_jobs_reply_route_object,
             check: "jsonb_typeof(reply_route) = 'object'"
           )

    create constraint(:automation_jobs, :automation_jobs_terminal_time_check,
             check:
               "(status = 'active' AND cancelled_at IS NULL) OR " <>
                 "(status = 'cancelled' AND cancelled_at IS NOT NULL) OR " <>
                 "status = 'expired'"
           )

    create constraint(:automation_job_runs, :automation_job_runs_id_range,
             check: "id >= 1000 AND id <= 9007199254740991"
           )

    create constraint(:automation_job_runs, :automation_job_runs_status_check,
             check: "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')"
           )

    create constraint(:automation_job_runs, :automation_job_runs_attempts_nonnegative,
             check: "attempts >= 0"
           )

    create constraint(:automation_job_runs, :automation_job_runs_event_object,
             check: "jsonb_typeof(event) = 'object' AND octet_length(event::text) <= 1048576"
           )

    create constraint(:automation_job_runs, :automation_job_runs_logs_bounded,
             check:
               "octet_length(stdout) <= 65536 AND octet_length(stderr) <= 65536 AND " <>
                 "octet_length(COALESCE(error, '')) <= 65536"
           )

    create constraint(:automation_job_runs, :automation_job_runs_lifecycle_check,
             check:
               "(status = 'queued' AND finished_at IS NULL AND attempt_id IS NULL) OR " <>
                 "(status = 'running' AND started_at IS NOT NULL AND finished_at IS NULL AND attempt_id IS NOT NULL) OR " <>
                 "(status IN ('succeeded', 'failed', 'cancelled') AND finished_at IS NOT NULL AND attempt_id IS NULL)"
           )
  end

  def down do
    alter table(:signal_gateway_webhook_endpoints) do
      remove :automation_job_id
    end

    alter table(:actor_cron_schedules) do
      remove :automation_job_id
    end

    alter table(:actor_scheduled_events) do
      remove :automation_job_run_id
      remove :automation_job_id
    end

    drop table(:automation_job_runs)
    drop table(:automation_jobs)
  end
end
