defmodule Ankole.Repo.Migrations.ResetActorScheduleIdentity do
  use Ecto.Migration

  @fire_worker "Elixir.Ankole.SignalsGateway.ActorRuntime.Jobs.FireScheduledEvent"

  def up do
    Enum.each(reset_sqls(), &execute/1)
  end

  def down do
    raise "Schedule history and UUID identifiers cannot be restored after the identity reset"
  end

  @doc false
  def reset_sqls do
    [
      "DELETE FROM oban_jobs WHERE worker = '#{@fire_worker}'",
      "DELETE FROM actor_scheduled_events",
      "DELETE FROM actor_cron_schedules",
      """
      DO $reset_actor_schedule_identity$
      DECLARE
        id_type text;
        id_is_identity text;
      BEGIN
        SELECT data_type, is_identity
        INTO id_type, id_is_identity
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'actor_scheduled_events'
          AND column_name = 'id';

        IF id_type = 'uuid' THEN
          ALTER TABLE actor_scheduled_events
            ALTER COLUMN id DROP DEFAULT,
            ALTER COLUMN id TYPE bigint USING NULL::bigint;
        ELSIF id_type IS DISTINCT FROM 'bigint' THEN
          RAISE EXCEPTION 'actor_scheduled_events.id has unsupported type %', id_type;
        END IF;

        IF id_is_identity = 'NO' THEN
          ALTER TABLE actor_scheduled_events
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000);
        END IF;

        IF NOT EXISTS (
          SELECT 1
          FROM pg_constraint
          WHERE conrelid = 'actor_scheduled_events'::regclass
            AND conname = 'actor_scheduled_events_id_range'
        ) THEN
          ALTER TABLE actor_scheduled_events
            ADD CONSTRAINT actor_scheduled_events_id_range
            CHECK (id >= 1000 AND id <= 9007199254740991);
        END IF;

        ALTER TABLE actor_scheduled_events
          ALTER COLUMN id RESTART WITH 1000;
      END
      $reset_actor_schedule_identity$;
      """
    ]
  end
end
