defmodule Ankole.Repo.Migrations.CreateWorkflowRuns do
  use Ecto.Migration

  def up do
    create table(:workflow_runs, primary_key: false) do
      add :id, :bigint, primary_key: true

      add :agent_uid,
          references(:principals, column: :uid, type: :text, on_delete: :delete_all),
          null: false

      add :owner_session_id, :text, null: false
      add :reply_route, :map, null: false, default: %{}
      add :source_actor_event_id, references(:actor_events, type: :uuid, on_delete: :nilify_all)
      add :source_tool_call_id, :text, null: false
      add :title, :text, null: false
      add :script, :text, null: false
      add :args, :map, null: false, default: %{}
      add :status, :text, null: false, default: "running"
      add :concurrency, :integer, null: false
      add :max_agent_calls, :integer, null: false
      add :memo_bytes, :integer, null: false, default: 0
      add :model_profile, :text
      add :result_text, :text
      add :error, :map, null: false, default: %{}
      add :completed_at, :utc_datetime_usec
      add :cleanup_completed_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    execute("""
    ALTER TABLE workflow_runs
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)
    """)

    create table(:workflow_agent_calls, primary_key: false) do
      add :id, :bigint, primary_key: true

      add :run_id,
          references(:workflow_runs, type: :bigint, on_delete: :delete_all),
          null: false

      add :agent_uid,
          references(:principals, column: :uid, type: :text, on_delete: :delete_all),
          null: false

      add :call_seq, :integer, null: false
      add :arguments, :map, null: false
      add :label, :text
      add :model_profile, :text
      add :status, :text, null: false, default: "queued"
      add :attempts, :integer, null: false, default: 0
      add :sleep_note, :text
      add :sleeping_until, :utc_datetime_usec
      add :wake_count, :integer, null: false, default: 0
      add :attention, :boolean, null: false, default: false
      add :result, :map
      add :error, :map, null: false, default: %{}

      timestamps(type: :utc_datetime_usec)
    end

    execute("""
    ALTER TABLE workflow_agent_calls
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)
    """)

    create unique_index(:workflow_runs, [:agent_uid, :owner_session_id, :source_tool_call_id],
             name: :workflow_runs_source_tool_call_index
           )

    create index(:workflow_runs, [:agent_uid, :status, :id],
             name: :workflow_runs_agent_status_index
           )

    create index(:workflow_runs, [:id],
             name: :workflow_runs_cleanup_pending_index,
             where: "cleanup_completed_at IS NULL"
           )

    create unique_index(:workflow_agent_calls, [:run_id, :call_seq],
             name: :workflow_agent_calls_run_sequence_index
           )

    create index(:workflow_agent_calls, [:run_id, :status],
             name: :workflow_agent_calls_run_status_index
           )

    create index(:workflow_agent_calls, [:agent_uid, :status],
             name: :workflow_agent_calls_agent_running_index,
             where: "status = 'running'"
           )

    create constraint(:workflow_runs, :workflow_runs_id_range,
             check: "id >= 1000 AND id <= 9007199254740991"
           )

    create constraint(:workflow_runs, :workflow_runs_owner_session_present,
             check: "length(btrim(owner_session_id)) > 0"
           )

    create constraint(:workflow_runs, :workflow_runs_source_tool_call_present,
             check: "length(btrim(source_tool_call_id)) > 0"
           )

    create constraint(:workflow_runs, :workflow_runs_reply_route_object,
             check: "jsonb_typeof(reply_route) = 'object'"
           )

    create constraint(:workflow_runs, :workflow_runs_title_valid,
             check: "length(btrim(title)) BETWEEN 1 AND 200"
           )

    create constraint(:workflow_runs, :workflow_runs_script_valid,
             check: "length(btrim(script)) > 0 AND octet_length(script) <= 262144"
           )

    create constraint(:workflow_runs, :workflow_runs_args_valid,
             check: "jsonb_typeof(args) = 'object'"
           )

    create constraint(:workflow_runs, :workflow_runs_status_check,
             check: "status IN ('running', 'completed', 'failed', 'cancelled')"
           )

    create constraint(:workflow_runs, :workflow_runs_concurrency_range,
             check: "concurrency BETWEEN 1 AND 32"
           )

    create constraint(:workflow_runs, :workflow_runs_max_agent_calls_range,
             check: "max_agent_calls BETWEEN 1 AND 1024"
           )

    create constraint(:workflow_runs, :workflow_runs_memo_bytes_range,
             check: "memo_bytes BETWEEN 0 AND 6291456"
           )

    create constraint(:workflow_runs, :workflow_runs_model_profile_valid,
             check: "model_profile IS NULL OR model_profile ~ '^[a-z][a-z0-9_-]{0,63}$'"
           )

    create constraint(:workflow_runs, :workflow_runs_result_bounded,
             check: "result_text IS NULL OR octet_length(result_text) <= 1048576"
           )

    create constraint(:workflow_runs, :workflow_runs_error_object,
             check: "jsonb_typeof(error) = 'object'"
           )

    create constraint(:workflow_runs, :workflow_runs_lifecycle_check,
             check:
               "(status = 'running' AND completed_at IS NULL) OR " <>
                 "(status IN ('completed', 'failed', 'cancelled') AND completed_at IS NOT NULL)"
           )

    create constraint(:workflow_runs, :workflow_runs_cleanup_lifecycle_check,
             check:
               "cleanup_completed_at IS NULL OR " <>
                 "status IN ('completed', 'failed', 'cancelled')"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_id_range,
             check: "id >= 1000 AND id <= 9007199254740991"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_sequence_nonnegative,
             check: "call_seq >= 0"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_arguments_valid,
             check: "jsonb_typeof(arguments) = 'object'"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_label_valid,
             check: "label IS NULL OR length(label) <= 200"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_model_profile_valid,
             check: "model_profile IS NULL OR model_profile ~ '^[a-z][a-z0-9_-]{0,63}$'"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_status_check,
             check:
               "status IN ('queued', 'running', 'sleeping', 'succeeded', 'failed', 'cancelled')"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_attempts_nonnegative,
             check: "attempts >= 0"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_wake_count_nonnegative,
             check: "wake_count >= 0"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_sleep_note_valid,
             check: "sleep_note IS NULL OR length(sleep_note) <= 200"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_sleeping_deadline_present,
             check: "status <> 'sleeping' OR sleeping_until IS NOT NULL"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_result_valid,
             check: "result IS NULL OR jsonb_typeof(result) = 'object'"
           )

    create constraint(:workflow_agent_calls, :workflow_agent_calls_error_object,
             check: "jsonb_typeof(error) = 'object'"
           )
  end

  def down do
    drop table(:workflow_agent_calls)
    drop table(:workflow_runs)
  end
end
