import { Elysia } from 'elysia'
import { appConfigService } from '@/config/app-configure'
import { AppEnv } from '@/config/env'
import { AppI18nDefaultLocaleConfig } from '@/config/i18n'
import { DEFAULT_LOCALE } from '@/config/i18n-locales'
import { redirectWithSetCookies } from '@/core/http'
import { activeHumanAdmin } from '@/principals/admin-auth/access'
import { readAdminSessionCookie } from '@/principals/admin-auth/session'
import { readSetupSessionCookie, setupSessionExpiredCookie } from '@/setup/session'
import { SetupCompletedConfig } from '@/setup/config'
import { type DevSpaHtmlRenderer, renderSpaHtml } from './spa-html'

type RedirectStatus = 301 | 302 | 303 | 307 | 308
type Redirect = (url: string, status?: RedirectStatus) => Response

interface WebAppRoutesOptions {
  devSpaHtmlRenderer?: DevSpaHtmlRenderer
}

/**
 * Server-owned HTML entry routes for the main React SPAs.
 *
 * The HTML itself is generated by Elysia handlers instead of static files so
 * setup, anonymous sign-in, and admin console can each enforce a different
 * cookie-session boundary before the browser downloads the matching SPA bundle.
 */
export function webAppRoutes(options: WebAppRoutesOptions = {}) {
  return new Elysia({ name: 'web-app-routes' })
    .get('/', async ({ redirect }) => {
      const completed = (await appConfigService.get(SetupCompletedConfig)) === true
      return redirect(completed ? '/sessions/new' : '/setup', 302)
    })
    .get('/setup', context => setupHtml(context, options))
    .get('/setup/*', context => setupHtml(context, options))
    .get('/sessions', context => sessionsHtml(context, options))
    .get('/sessions/*', context => sessionsHtml(context, options))
    .get('/console', context => consoleHtml(context, options))
    .get('/console/*', context => consoleHtml(context, options))
}

/** Serves setup only before bootstrap finishes, then clears stale setup cookies before redirecting home. */
async function setupHtml(
  { request, redirect }: { request: Request; redirect: Redirect },
  options: WebAppRoutesOptions
) {
  const completed = (await appConfigService.get(SetupCompletedConfig)) === true
  if (completed) {
    const setupSession = readSetupSessionCookie(request.headers.get('cookie'))
    if (setupSession) return redirectWithSetCookies('/', [setupSessionExpiredCookie(AppEnv.IS_PRODUCTION)])

    return redirect('/', 302)
  }

  return renderSpaHtml({
    app: 'setup',
    title: 'BullX Setup',
    locale: await appLocale(),
    request,
    devRenderer: options.devSpaHtmlRenderer
  })
}

/** Serves anonymous sign-in after setup and redirects active admins straight to the console. */
async function sessionsHtml(
  { request, redirect }: { request: Request; redirect: Redirect },
  options: WebAppRoutesOptions
) {
  const completed = (await appConfigService.get(SetupCompletedConfig)) === true
  if (!completed) return redirect('/setup', 302)

  const setupSession = readSetupSessionCookie(request.headers.get('cookie'))
  if (setupSession) {
    const url = new URL(request.url)
    return redirectWithSetCookies(`${url.pathname}${url.search}`, [setupSessionExpiredCookie(AppEnv.IS_PRODUCTION)])
  }

  const adminSession = readAdminSessionCookie(request.headers.get('cookie'))
  if (adminSession && (await activeHumanAdmin(adminSession.principalUid))) return redirect('/console', 302)

  return renderSpaHtml({
    app: 'sessions',
    title: 'BullX Sign In',
    locale: await appLocale(),
    request,
    devRenderer: options.devSpaHtmlRenderer
  })
}

/** Protects the admin console HTML route before the browser can download the console SPA bundle. */
async function consoleHtml(
  { request, redirect }: { request: Request; redirect: Redirect },
  options: WebAppRoutesOptions
) {
  const completed = (await appConfigService.get(SetupCompletedConfig)) === true
  if (!completed) return redirect('/setup', 302)

  const adminSession = readAdminSessionCookie(request.headers.get('cookie'))
  if (!adminSession || !(await activeHumanAdmin(adminSession.principalUid))) {
    const url = new URL(request.url)
    const returnTo = `${url.pathname}${url.search}`
    return redirect(`/sessions/new?return_to=${encodeURIComponent(returnTo)}`, 302)
  }

  return renderSpaHtml({
    app: 'console',
    title: 'BullX Console',
    locale: await appLocale(),
    request,
    devRenderer: options.devSpaHtmlRenderer
  })
}

/** Resolves the locale for HTML bootstrapping from config, falling back to the bundled default. */
async function appLocale(): Promise<string> {
  return (await appConfigService.get(AppI18nDefaultLocaleConfig)) ?? DEFAULT_LOCALE
}
