import { Elysia } from 'elysia'
import { appConfigService } from '@/config/app-configure'
import { AppEnv } from '@/config/env'
import { redirectWithSetCookies } from '@/core/http'
import { activeHumanAdmin } from '@/principals/admin-auth/access'
import { readAdminSessionCookie } from '@/principals/admin-auth/session'
import { readSetupSessionCookie, setupSessionExpiredCookie } from '@/setup/session'
import { SetupCompletedConfig } from '@/setup/config'
import { renderSpaHtml } from './spa-html'

type RedirectStatus = 301 | 302 | 303 | 307 | 308
type Redirect = (url: string, status?: RedirectStatus) => Response

/**
 * Server-owned HTML entry routes for the three React SPAs.
 *
 * The HTML itself is generated by Elysia handlers instead of static files so
 * setup, anonymous sign-in, and admin console can each enforce a different
 * cookie-session boundary before the browser downloads the matching SPA bundle.
 */
export function webAppRoutes() {
  return new Elysia({ name: 'web-app-routes' })
    .get('/', async ({ redirect }) => {
      const completed = (await appConfigService.get(SetupCompletedConfig)) === true
      return redirect(completed ? '/sessions/new' : '/setup', 302)
    })
    .get('/setup', setupHtml)
    .get('/setup/*', setupHtml)
    .get('/sessions', sessionsHtml)
    .get('/sessions/*', sessionsHtml)
    .get('/console', consoleHtml)
    .get('/console/*', consoleHtml)
}

async function setupHtml({ request, redirect }: { request: Request; redirect: Redirect }) {
  const completed = (await appConfigService.get(SetupCompletedConfig)) === true
  if (completed) {
    const setupSession = readSetupSessionCookie(request.headers.get('cookie'))
    if (setupSession) return redirectWithSetCookies('/', [setupSessionExpiredCookie(AppEnv.IS_PRODUCTION)])

    return redirect('/', 302)
  }

  return renderSpaHtml({
    app: 'setup',
    title: 'BullX Setup'
  })
}

async function sessionsHtml({ request, redirect }: { request: Request; redirect: Redirect }) {
  const completed = (await appConfigService.get(SetupCompletedConfig)) === true
  if (!completed) return redirect('/setup', 302)

  const setupSession = readSetupSessionCookie(request.headers.get('cookie'))
  if (setupSession) {
    const url = new URL(request.url)
    return redirectWithSetCookies(`${url.pathname}${url.search}`, [setupSessionExpiredCookie(AppEnv.IS_PRODUCTION)])
  }

  const adminSession = readAdminSessionCookie(request.headers.get('cookie'))
  if (adminSession && (await activeHumanAdmin(adminSession.principalUid))) return redirect('/console', 302)

  return renderSpaHtml({
    app: 'sessions',
    title: 'BullX Sign In'
  })
}

async function consoleHtml({ request, redirect }: { request: Request; redirect: Redirect }) {
  const completed = (await appConfigService.get(SetupCompletedConfig)) === true
  if (!completed) return redirect('/setup', 302)

  const adminSession = readAdminSessionCookie(request.headers.get('cookie'))
  if (!adminSession || !(await activeHumanAdmin(adminSession.principalUid))) {
    const url = new URL(request.url)
    const returnTo = `${url.pathname}${url.search}`
    return redirect(`/sessions/new?return_to=${encodeURIComponent(returnTo)}`, 302)
  }

  return renderSpaHtml({
    app: 'console',
    title: 'BullX Console'
  })
}
